index.js, lib/android-helpers.js, lib/commands/general.js, lib/commands/index.js, lib/desired-caps.js, lib/driver.js, lib/server.js, package.json, test/functional/android-helper-e2e-specs.js, test/functional/driver-e2e-specs.js, test/unit/android-helper-specs.js, test/unit/driver-specs.js
making this so I can add comments @moizjv @Jonahss
=> MJ merge into master

lib/commands/element.js, lib/commands/general.js
=> element attribute commands

lib/commands/actions.js, lib/commands/index.js
@Jonahss not TDD just brutal transpiling by a human!
=> Adding action commands

lib/android-helpers.js, lib/commands/element.js, lib/commands/index.js, lib/commands/touch.js, test/unit/touch-specs.js
@imurchie @sebv @Jonahss @jlipps please take a look. 
I have tested them with our functional tests and they work fine.
=> Adding touch commands

index.js, lib/desired-caps.js
so selendroid can use them.
ping @Jonahss @moizjv for a quick review
=> split out and export common android capability constraints

lib/android-helpers.js, lib/commands/general.js, lib/commands/ime.js, lib/commands/index.js, lib/driver.js
@jlipps @moizjv @Jonahss please review.
=> Added IME commands

lib/commands/context.js, lib/desired-caps.js
- This cap can address issues where webview has changed.
=> Adding recreateChromeDriverSessions cap

test/functional/driver-e2e-specs.js
=> Adding negative tests for create session

gulpfile.js, lib/android-helpers.js, lib/commands/alert.js, lib/commands/context.js, lib/commands/general.js, lib/commands/ime.js, lib/commands/network.js, lib/desired-caps.js, lib/driver.js, package.json, test/functional/driver-e2e-specs.js
- Style cleanup.
- Commands: get/set/accept/dismiss alert.
- Resolved TODO: validate capabilities (app, app package, browser).
- Resolved TODO: document recreateChromeDriverSessions.
- Resolved TODO: throw an error if appPackage isn't found on device.
- Additional tests.
=> 1.5 cleanup - Todos, style

lib/commands/context.js, lib/driver.js, package.json
to avoid regressing from current appium behavior.
cc @aluedeke
ping @moizjv @Jonahss for review
=> make sure to start chromedrivers with reference to the correct adb server port

lib/android-helpers.js, test/unit/android-helper-specs.js
Fix regex and add test. Supersedes #59
=> Allow openjdk

lib/commands/network.js, lib/desired-caps.js, lib/driver.js
Necessary change to make appium-android-bootstrap#10 work
Original PR https://github.com/appium/appium/pull/5838
=> Accept SSL certs

test/functional/api-demos/attribute-e2e-specs.js
Test from PR appium/appium#5189 lives now here.
_Todo:_ publish appium-android-bootstrap after appium/appium-android-bootstrap#11 landed
=> added test for contentdescription pr

lib/android-helpers.js, lib/commands/general.js, lib/driver.js
=> getStrings fix, setting ADB java version to 2.0

lib/commands/actions.js, lib/driver.js
Also make sure all the commands are async.
=> Sanitize orientation

lib/driver.js
Resolves https://github.com/appium/appium/issues/5946
=> return merged server + desired caps on createSession

README.md, lib/commands/general.js
@Jonahss Do we have any method existing to get current device id for android? Also please review.
=> added a new command for getting device date and time

lib/commands/general.js, test/functional/driver-e2e-specs.js
@imurchie @jlipps please review!
=> Adding closeApp functionality and test

lib/webview-helpers.js
Ports PR https://github.com/appium/appium/pull/6007 to 1.5 which fixes issue https://github.com/appium/appium/issues/5689
cc) @imurchie
=> ported PR #6007 - Android 6 procFromWebview fix

package.json
Fixes issues with launching certain activities.
=> Bump adb version

lib/commands/general.js, test/functional/commands/general-e2e-specs.js
There is much more that can be sent to the function. See https://github.com/appium/appium/issues/6097
=> Add optional arguments to startActivity

lib/commands/actions.js, package.json, test/functional/commands/actions-e2e-specs.js
Parameters were switched around.
Fixes https://github.com/appium/appium/issues/6101
=> Fix replaceValue method

lib/commands/general.js, test/functional/commands/general-e2e-specs.js
Addresses https://github.com/appium/appium/issues/6114
=> Add tests for startActivity with dontStopAppOnReset

package.json
=> Udpate chromedriver

lib/commands/actions.js, lib/commands/element.js
We need to make sure that `setValue` and `replaceValue` work in the same way.
Fixes https://github.com/appium/appium/issues/6142
=> Fix replaceValue parameters

lib/driver.js, package.json
Addresses https://github.com/appium/appium/issues/6202
=> Make use of bootstrap port argument

lib/desired-caps.js
Reported https://github.com/appium/java-client/issues/302#issuecomment-193196702
=> Fix keystorePassword to be a string

lib/driver.js
Resolves https://github.com/appium/appium/issues/6235
=> Unlock the device for chrome sessions too

lib/commands/find.js
Will work in combination with: https://github.com/appium/appium-android-bootstrap/pull/17
=> Enable support for xpath find commands on elements

lib/commands/general.js, test/functional/commands/keyboard-e2e-specs.js
Port old keyboard tests into new driver.
=> Add keyboard tests

README.md, lib/android-helpers.js, lib/driver.js
Port over https://github.com/appium/appium/pull/5807
Should resolve https://github.com/appium/appium/issues/6393
=> Add chromium browser

lib/commands/touch.js, test/functional/commands/touch/drag-e2e-specs.js, test/unit/commands/touch-specs.js
Make sure we are actually fixing the release. Otherwise we end up throwing errors.
Fixes https://github.com/appium/appium/issues/6416
=> Fix release handling

lib/commands/actions.js, test/unit/commands/actions-specs.js
We had the entirely wrong implementation for flick. Not sure why.
Fixes #134
=> Fix flick handling

lib/driver.js, test/unit/driver-specs.js
Fixes https://github.com/appium/appium/issues/6420
=> Implement autoWebviewTimeout

package.json, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/functional/commands/keyboard-e2e-specs.js
Make sure that Unicode strings get through the stack.
=> Add test for unicode through find

lib/driver.js
So they are available to the test in the return from creating a session.
See https://github.com/appium/appium/issues/6448
=> Add appPackage and appActivity to the caps

lib/commands/network.js, test/unit/commands/network-specs.js
Fixes: appium/appium#5256
@imurchie @jlipps @TikhomirovSergey Please review. This fixes the API to work on all the Android API till API Level 23 (Tested from 19 to 23)
=> Fix for setNetworkConnection API

lib/commands/element.js, test/functional/commands/keyboard-e2e-specs.js
Make use of `adb.clearTextField` to try to clear better in Android.
=> Update clear, and tests

lib/commands/element.js, lib/commands/find.js, lib/commands/touch.js
As per the suggestions made in appium-uiautoamtor2-driver [PR](https://github.com/appium/appium-uiautomator2-driver/pull/26), refactored findElOrEls, setElementValue and performMultiAction implementations to avoid code duplication.
- Refactored [find.js](https://github.com/sravanmedarapu/appium-android-driver/blob/master/lib/commands/find.js#L30) to invoke corresponding driver implementation of [`doFindElementOrEls()`](https://github.com/sravanmedarapu/appium-android-driver/blob/master/lib/commands/find.js#L46)
1. appium-android-driver implementation [refer](https://github.com/sravanmedarapu/appium-android-driver/blob/master/lib/commands/find.js#L7)
1. appium-uiautomator2-driver implementation  [refer](https://github.com/sravanmedarapu/appium-uiautomator2-driver/blob/948be847bfab33384fdcfc …
=> Refactored find.js, touch.js, element.js

lib/commands/general.js
The parameters to `installApkRemotely` were changed but two places were missed.
Cc: @spearminty
=> Fix remaining installApkRemotely calls

lib/commands/context.js, package.json
=> Use random available port for ChromeDriver sessions

lib/commands/actions.js
Changes in this PR are with respective to the changes [here.](https://github.com/appium/appium-uiautomator2-driver/pull/29) Removed redundant code in appium-uiautomator2-driver
=> Seperated SwipeOpts and SwipeActionCall to extend swipeOpts to uiautomator2

lib/commands/actions.js, lib/commands/general.js
- Refactored Drag, Swipe and Keys
=> Refactored Drag, Swipe & Keys

lib/android-helpers.js, lib/commands/general.js, test/unit/android-helper-specs.js
=> fix incorrect parameter key in installApp (fix appium/appium#6695)

lib/commands/network.js
To implement WIFI actions in UIAutomator2 Driver.
Issue: #https://github.com/appium/appium/issues/6615
=> decouple isWifiOn and toggleWifi

lib/driver.js, package.json, test/functional/driver-e2e-specs.js
#https://github.com/appium/appium-adb/pull/189
#https://github.com/appium/appium/issues/7497
@imurchie, @jlipps
=> added grant permissions

lib/commands/performance.js, package.json, test/functional/android-helper-e2e-specs.js, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/functional/commands/keyboard-e2e-specs.js, test/functional/commands/localization/language-e2e-specs.js, test/functional/commands/network-e2e-specs.js, test/functional/commands/notifications-e2e-specs.js, test/functional/commands/performance-e2e-specs.js, test/functional/commands/touch/drag-e2e-specs.js, test/functional/commands/url-e2e-specs.js, test/functional/desired.js, test/functional/driver-e2e-specs.js, test/unit/commands/performance-specs.js
Quarantine a number of tests (see https://github.com/appium/appium/issues/7707).
Fix performance API and its tests.
=> Update to pass on different API levels

lib/commands/context.js, lib/desired-caps.js
This will allow us to to connect to multiple apps with webivew in same test session.
=> Capability to extract chromeAndroidPackagee from context_name

lib/driver.js, package.json, test/functional/driver-e2e-specs.js, test/unit/driver-specs.js
Depends on #https://github.com/appium/appium-adb/pull/195
Req Ticket: #https://github.com/appium/appium/issues/3210
cc: @jlipps, @imurchie
=> Added device screen size, model and manufacturer details to session

lib/driver.js
False indication in error message.
Fixes https://github.com/appium/appium/issues/7759
=> Change error text for no app, etc.

lib/desired-caps.js, test/functional/commands/performance-e2e-specs.js, test/functional/desired.js
Make sure the driver knows about the cap. Also fix some naming on tests.
=> Add autoGrantPermissions to caps list

lib/commands/general.js
Addresses https://github.com/appium/appium/issues/7810
=> Grant permissions in reset flow

lib/android-helpers.js, lib/commands/network.js, lib/driver.js, test/unit/android-helper-specs.js, test/unit/commands/network-specs.js
Please merge the PR after https://github.com/appium/appium-adb/pull/208 and https://github.com/appium/io.appium.settings/pull/7 are merged and published
=> Fix for Appium Settings app install and network state change

docs/UNLOCK.md
Sorry, I left the branch name in the screenshot url and it's not showing them in the UNLOCK.md. 
Please review @jlipps @imurchie
=> Fix unlock screenshot url... again

.travis.yml, README.md, lib/commands/context.js, lib/commands/touch.js, lib/server.js, test/functional/android-helper-e2e-specs.js, test/functional/chrome-e2e-specs.js, test/functional/commands/localization/language-e2e-specs.js, test/functional/commands/notifications-e2e-specs.js, test/functional/commands/performance-e2e-specs.js, test/functional/desired.js, test/functional/driver-e2e-specs.js, test/functional/helpers.js, test/functional/webview-browser-tester-e2e-specs.js
Preliminary work to get functional tests running on Travis so there is at least a smoke test, since our dedicated CI is currently offline.
After this I will explore a more involved script to allow us to test on different platforms, and look into the tests that are quarantined to see why they are failing on Travis.
=> Try out Android Travis config

README.md, test/functional/helpers.js, test/functional/webview-browser-tester-e2e-specs.js, test/unit/android-helper-specs.js, test/unit/commands/performance-specs.js, test/unit/test-helper-specs.js
While on a wifi-less flight I removed the google.com dependency in this test. Also un-skipped the remaining unit tests that were skipped.
=> Move chromium-webview browser test to use internal server

lib/commands/actions.js, package.json, test/unit/commands/actions-specs.js
* Wrote a test for `commands.pullFolder` that verifies it works correctly with adm-zip
* Removed adm-zip dependency and made the test fail
* Added appium support zip dependency and replaced it with that and made the tests work again
=> Remove adm-zip dependency

.travis.yml, test/functional/commands/keyboard-e2e-specs.js, test/functional/commands/localization/language-e2e-specs.js
Forgot that `mocha` on its own does not recurse into subdirectories.
=> Make all functional tests run in Travis

lib/commands/actions.js, lib/driver.js, package.json, test/unit/driver-specs.js
Integrate *appium-adb* `.sendSMS` method
=> Add sendSMS method

test/unit/webview-helper-specs.js
I've added some tests to cover existing functionality in webview-helpers.js that I'd like to contribute.
=> Add tests for webview-helpers.js to cover existing functionality

lib/android-helpers.js, lib/desired-caps.js, lib/driver.js
Promote `remoteAdbHost` as a desired capability (https://github.com/appium/appium/issues/8564)
=> Add remoteAdbHost to desired caps

.travis.yml, lib/android-helpers.js
Before trying to determine device, trim the platformVersion so it is just a string. See https://github.com/appium/appium/issues/8851
=> Trim platformVersion

.travis.yml, package.json
No need for global `gulp` and `mocha`.
=> Move to npm scripts

lib/commands/network.js, lib/desired-caps.js, lib/driver.js, package.json, test/unit/commands/network-specs.js
Add possibility to enable/disable GPS on emulators before running apps by adding gpsEnabled capability.
=> Add gpsEnabled capability

package-lock.json, package.json, test/functional/commands/keyboard/keyboard-e2e-specs.js
The apidemos app now mirrors the password field contents, so we can assert on it.
=> Add assertion to password field typing test

lib/android-helpers.js, lib/desired-caps.js, test/unit/android-helper-specs.js
Add isHeadless capability to make the emulator to launch headless.
=> Add isHeadless capability

lib/commands/actions.js, test/functional/commands/keyboard/keyboard-e2e-specs.js, test/unit/android-helper-specs.js, test/unit/commands/actions-specs.js, test/unit/commands/element-specs.js, test/unit/commands/find-specs.js, test/unit/commands/general-specs.js, test/unit/commands/ime-specs.js, test/unit/commands/touch-specs.js, test/unit/driver-specs.js
* Add tests for commands modules: [actions, element, find, general, ime]
* Add tests for android-helpers.ensureNetworkSpeed()
* Attach getScreenshotDataWithAdbExecOut and
getScreenshotDataWithAdbShell to helpers in actions.js
* Tests that related to actions.js was moved from driver-specs.js to
actions-specs.js
* Tests that related to driver.initAUT() was moved from general-specs.js
to driver-specs.js
=> Add tests for commands modules: [actions, element, find, general, ime]

lib/desired-caps.js
This should improve parallel sessions management
=> Add chromeDriverPort to capabilities list

lib/commands/actions.js, test/unit/commands/actions-specs.js
Improve the way files are pushed and pulled to/from the device
=> Always assume the file to be pushed contains binary data

lib/commands/actions.js, test/unit/commands/actions-specs.js
Add error handling to try to be able to trace problems like https://github.com/appium/appium/issues/9369
=> Update exec-out screenshot

lib/driver.js, test/functional/commands/basic/orientation-e2e-specs.js
Make `orientation`  capability work. Resolves https://github.com/appium/appium/issues/9391
=> Add initial orientation functionality

lib/android-helpers.js, package-lock.json, package.json, test/functional/android-helper-e2e-specs.js, test/unit/android-helper-specs.js
Update logic for making sure we can install over the unlock and settings app.
=> Fix handling of settings and unlock app pushing

lib/android-helpers.js
Addresses https://github.com/appium/appium/issues/9531
=> Make sure the platformVersion is of String type

lib/android-helpers.js, lib/commands/performance.js, package.json, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/functional/commands/notifications-e2e-specs.js, test/functional/commands/performance-e2e-specs.js, test/functional/driver-e2e-specs.js, test/unit/android-helper-specs.js, test/unit/commands/performance-specs.js
now _adb.getApiLevel_ call always returns an integer
=> Update appium-adb module

lib/commands/actions.js, test/unit/commands/actions-specs.js
Addresses https://github.com/appium/appium/issues/6692
=> Add  a possibility to pull/push files from/to application containers

lib/android-helpers.js, lib/commands/context.js, lib/commands/touch.js, lib/driver.js, lib/webview-helpers.js, package.json, test/functional/commands/keyboard/keyboard-e2e-specs.js
See https://github.com/appium/appium/issues/9866
=> Update to lodash 4

lib/android-helpers.js
This will fix https://github.com/appium/appium/issues/9944
=> move the time to install setting app

lib/commands/context.js
Addresses https://github.com/appium/appium/issues/9978
=> Fix TypeError by Chrome driver detection

lib/driver.js
Data can be wiped from the user side via `avdAgs` capability.
=> Don't force `wipe-data`, if the `reboot` capability is provided.

lib/commands/actions.js
Applied the same workaround as for https://github.com/appium/appium-xcuitest-driver/pull/605
=> Add client issue workaround for pushFile endpoint

README.md, lib/commands/general.js, test/unit/commands/general-specs.js
This implementation is for Android driver.
As same as : https://github.com/appium/appium-xcuitest-driver/pull/607
=> Add rect for window

lib/android-helpers.js
There was a typo in the previous one %)
=> Tune log message

lib/android-helpers.js, lib/commands/general.js, lib/driver.js, package.json, test/functional/android-helper-e2e-specs.js, test/unit/android-helper-specs.js, test/unit/commands/general-specs.js, test/unit/driver-specs.js
The PR depends on https://github.com/appium/appium-adb/pull/290
=> Update and refactor application installation helpers

lib/commands/app-management.js, lib/commands/general.js, lib/commands/index.js, test/unit/commands/general-specs.js
Also added some missing async/await pairs. For good.
=> Fix application management endpoints

lib/commands/app-management.js, test/unit/commands/general-specs.js
This will clean up the temporary package if it was downloaded from a remote location
=> Update installApp to remove temporary application packages

lib/commands/actions.js
should help with pushing photos
=> if we are pushing a media file, broadcast the rescan intent

lib/commands/general.js, package.json, test/unit/commands/general-specs.js
Addresses https://github.com/appium/appium/issues/4446 and https://github.com/appium/appium/issues/5032
=> Add 'bugreport' and 'server' log types

lib/commands/general.js, lib/commands/index.js, lib/commands/log.js, package.json, test/unit/commands/general-specs.js, test/unit/commands/log-specs.js
Use logging commands from https://github.com/appium/appium-base-driver/pull/191. Re-implements functionality from https://github.com/appium/appium-android-driver/pull/338
=> Use base driver logging methods

lib/commands/log.js
Addresses https://github.com/appium/appium/issues/10355
=> Fix logger unwrap

lib/commands/log.js
Fixes https://github.com/appium/appium/issues/10355#issuecomment-373435982
=> Tune log records format to make clients happy

lib/android-helpers.js, lib/commands/execute.js, lib/commands/log.js, lib/driver.js, lib/server.js, package.json, test/functional/logs-e2e-specs.js
Based on https://github.com/appium/appium-adb/pull/306
=> Add a possibility to broadcast logcat output via websocket

lib/commands/performance.js
Addresses https://github.com/appium/appium/issues/10384
=> Fix regular expressions for perf data collection

lib/android-helpers.js, lib/desired-caps.js, lib/driver.js, test/unit/android-helper-specs.js, test/unit/driver-specs.js
* Augmented initAUT to install apk's if a JSON array or string was provided in capability called 'otherApps'
* Goes through the list and downloads (if URL) the apps asynchronously and then installs all of them asynchronously using ADB install
(next step will be to document in caps.md)
=> Add 'otherApps' capability

lib/commands/log.js, package.json
This resolves possible memory leak while closing logcat web socket listener
=> Fix logcat listener removal

lib/commands/general.js, lib/desired-caps.js, package.json, test/unit/commands/general-specs.js
Depends on https://github.com/appium/appium-adb/pull/318
=> Add a possibility to set user profile index while launching applications

lib/android-helpers.js
Fixed by @myso-kr in https://github.com/appium/appium/issues/10610
=> Fix passing suppressKillServer option while creating ADB instance

lib/commands/recordscreen.js
Addresses https://github.com/appium/appium/issues/10630
=> Fix FTP protocol detection

lib/commands/context.js, lib/commands/element.js, lib/commands/general.js, lib/commands/touch.js
I have created a small helper tool for finding missing await calls. It is pretty dumb yet, but managed to find some issues so far.
=> Add missing await

lib/android-helpers.js, lib/commands/context.js, lib/commands/find.js, package.json, test/functional/commands/find/by-uiautomator-e2e-specs.js, test/unit/commands/find-specs.js
Update `appium-chromedriver` and pass in the bundle id of the chrome process, so that webview handling works as expected.
Also, recent changes to `appium-android-bootstrap` necessitate changing the find method, and some tests.
=> Pass chrome bundle id into CD when possible

lib/android-helpers.js
See https://github.com/appium/appium/issues/10627
=> Extract basic adb creation into helper function

lib/commands/find.js, test/unit/commands/find-specs.js
Addresses https://github.com/appium/appium/issues/10809
=> Fix implicit wait for finding elements

lib/android-helpers.js, test/unit/android-helper-specs.js
Related to [9444](https://github.com/appium/appium/issues/9944) 
This error occurs when trying to change the language on an emulator.
=> Install settings app on AVD for Locales

lib/commands/general.js, test/unit/commands/general-specs.js
Depends on _tweak android date format #377_
Added `format` to make the customisable format of `adb date`.
=> Add custom format option

lib/android-helpers.js, lib/driver.js
..So then it can be reused in UIA2 without extra code duplication
=> Move common caps verification to helpers module

lib/driver.js, test/unit/driver-specs.js
Addresses https://github.com/appium/appium/issues/10975
=> Add deprecation warning for newer Android versions

test/functional/commands/find/by-uiautomator-e2e-specs.js
Add a quick test to ensure parsing of UiAutomator code works correctly.
=> Add test with multiple commas in uiautomator code

lib/commands/recordscreen.js, test/unit/commands/recordscreen-specs.js
Addresses https://github.com/appium/appium/issues/11117
=> Make sure that file exists instead of checking its size

lib/commands/recordscreen.js, package.json, test/unit/commands/recordscreen-specs.js
https://discuss.appium.io/t/detect-when-adb-stops-recording-screen
=> Add a possibility to record longer videos in Android

lib/desired-caps.js, lib/driver.js
This might sometimes seriously reduce element lookup delays
=>  Add a capability to disable window animations

lib/commands/recordscreen.js
Also, improved the error message for the incorrect timeout value for screen recording
=> Adjust heap size calculation for a large file

lib/commands/recordscreen.js
Addresses https://github.com/appium/appium/issues/11276
=> Terminate the background screen recorder with sigint instead of sigterm

lib/commands/network.js, package.json, test/unit/commands/network-specs.js
This should works for both real devices and emulators as long as Appium Settings is installed there.
=> Add get geolocation handler

bootstrap/src/io/appium/android/bootstrap/handler/WaitForIdle.java
improve handler WaitForIdle's documentation
=> improve documentation

lib/commands/network.js, test/unit/commands/network-specs.js
Addresses https://github.com/appium/appium/issues/7400
=> Return the current location from setGeoLocation

lib/android-helpers.js, test/unit/android-helper-specs.js
Addresses https://github.com/appium/appium/issues/11412
=> Send custom keystore options to ADB

lib/android-helpers.js, package.json, test/functional/android-helper-e2e-specs.js, test/unit/android-helper-specs.js
The PR depends on https://github.com/appium/io.appium.settings/pull/19
=> Deprecate unlock helper apk

lib/commands/context.js, lib/desired-caps.js, package.json
Pass the `disableBuildCheck` flag into `appium-chromedriver`.
=> Add chromedriverDisableBuildCheck cap

test/functional/commands/basic/language-e2e-specs.js
Fix locale e2e to work for all devices
- https://github.com/appium/appium-adb/pull/393
- Update appium-adb to the latest version 🚀 #481
=> use setDeviceLocale to set locale

lib/unlock-helpers.js, test/unit/unlock-helper-specs.js
I don't see a need to have a separate helper method, which only contains single function call.
=> Merge wakeUp helper to dismissKeyguard

lib/driver.js
As same as https://github.com/appium/appium-uiautomator2-driver/pull/291 .
=> move disabling animation before autoLaunch check

index.js, lib/android-helpers.js, lib/desired-caps.js, lib/driver.js, test/unit/driver-specs.js
Would like to add a new cap which uninstalled packages in initialising phase.
The use case is similar to `otherApps`, Appium installs specified packages by it.
=> Add uninstallpcackages

lib/android-helpers.js, lib/desired-caps.js, lib/driver.js, test/unit/android-helper-specs.js, test/unit/driver-specs.js
Add ability to disable logcat capture 
https://github.com/appium/appium/issues/12203
cc @sshock
=> add skipLogcatCapture

lib/commands/execute.js, lib/commands/general.js
https://github.com/appium/appium/issues/12296
=> Add mobile commands for interaction with package permissions

test/unit/unlock-helper-specs.js
(fixes tests for https://github.com/appium/appium-android-driver/pull/489)
=> Fix unlock unit test

lib/android-helpers.js, test/unit/android-helper-specs.js
Monkey seem to be more stable than startApp call, which randomly fails on Travis
=> Prefer monkey tool to activate settings app

lib/commands/context.js, test/functional/chrome-e2e-specs.js, test/functional/desired.js, test/functional/webview-browser-tester-e2e-specs.js
It turns out that Chrome hangs if this is used. On versions of Chrome supported by the Android driver, this is not going to be possible.
=> Undo using existing Chrome if noReset is true

README.md, lib/commands/log.js, lib/commands/shell.js, package.json
depends on https://github.com/appium/appium-base-driver/pull/328
=> use isFeatureEnabled for security features check

lib/commands/general.js
https://github.com/appium/appium-uiautomator2-driver/pull/327/files for background app
=> feat: add this.opts.appWaitForLaunch

package.json, test/functional/commands/file-movement-e2e-specs.js
https://npmjs.com/advisories/886
=> Stop using the vulnerable unzip dev dependency

lib/desired-caps.js
There capabilities must be also available uia2 and espresso
=> fix: Move common capabilities to the appropriate place

lib/android-helpers.js, lib/driver.js
This is needed to finish https://github.com/appium/appium-uiautomator2-driver/pull/337
=> chore: Move parts of capabilities validation to the driver code

lib/commands/app-management.js
Addresses https://github.com/appium/appium/issues/13420
=> fix: Update queryAppState API for Android 10+

package.json
=> fix(package): update jimp to version 0.9.3

test/functional/driver-e2e-specs.js
Addresses https://travis-ci.org/appium/appium-android-driver/jobs/623801974#L4957
=> chore: Update the failing integration test after fixes in appium-adb

lib/driver.js, package.json, test/unit/driver-specs.js
Based on appium/appium-base-driver#374
=> fix: Avoid applications cache corruption

lib/commands/recordscreen.js
https://github.com/appium/appium/issues/13921
=> docs: Fix the units for bitRate value

lib/webview-helpers.js, package.json, test/unit/webview-helper-specs.js
I've slightly simplified the logic there and moved package name retrieval into appium-adb, where it is supposed to be
=> refactor: Update web view helpers

lib/commands/emu-console.js, lib/commands/execute.js, lib/commands/index.js, lib/commands/shell.js, package.json
Related to https://github.com/appium/appium/issues/6028
Based on https://github.com/appium/appium-adb/pull/517
=> feat: Add mobile command for emulator console feature

lib/android-helpers.js, lib/desired-caps.js
https://github.com/appium/appium/issues/8969
=> feat: Make location mock configurable

lib/commands/recordscreen.js, package.json
Added the new options for the recent appium-support update
=> chore: Update file upload procedure

lib/android-helpers.js, lib/desired-caps.js, lib/driver.js, package.json, test/unit/android-helper-specs.js, test/unit/driver-specs.js
Based on https://github.com/appium/appium-adb/pull/524
Also added a possibility to provide emulator env using `avdEnv` capability
=> chore: Bump appium-adb version

lib/android-helpers.js, lib/desired-caps.js
Based on https://github.com/appium/appium-adb/pull/528
=> feat: Add support for logcat output customization

lib/commands/log.js, package.json
https://github.com/appium/appium/issues/3412
=> feat: Make it possible to retrieve native logs being in web context

lib/commands/execute.js, lib/commands/index.js, lib/commands/services.js
https://github.com/appium/appium/issues/10382
=> feat: Add mobile helpers to handle services

.azure-pipelines.yml
Include only npm for now.
Other tests require Android emulator will be later
=> ci: Set up CI with Azure Pipelines

lib/driver.js
Related to https://github.com/appium/appium-uiautomator2-driver/pull/439
=> fix: Make sure screen recording stops after a session is closed

lib/commands/file-actions.js, test/unit/commands/file-actions-specs.js
Fixes https://github.com/appium/appium/issues/15156
=> fix: Update the command to copy a file to/from a bundle

lib/commands/context.js, lib/webview-helpers.js
Fixes https://github.com/appium/appium/issues/15272
=> fix: Respect androidProcess during web view creation

docs/UNLOCK.md
https://github.com/appium/appium-android-driver/pull/691
=> docs: add pinWithKeyEvent in unlock.md

lib/webview-helpers.js
Addresses https://github.com/appium/appium/issues/15523
=> fix: Only set androidProcess if PID can be identified

lib/commands/app-management.js, lib/commands/execute.js
It is sometimes useful to clear app data during the test
=> feat: Add a mobile extension to clear an app data

lib/android-helpers.js, lib/commands/execute.js, lib/commands/general.js, lib/desired-caps.js, lib/unlock-helpers.js, test/unit/android-helper-specs.js
Just in case someone still needs to use the legacy approach. Also added a mobile helper for the stuff
=> feat: Make unlocking strategy configurable

lib/commands/performance.js, test/unit/commands/performance-specs.js
The PR is just a refactoring of https://github.com/appium/appium-android-driver/pull/717 by @YueChen-C
=> fix: Update parse memory data for Android 11(API 30)

lib/commands/general.js, lib/commands/index.js, lib/commands/system-bars.js, test/unit/commands/general-specs.js, test/unit/commands/systems-bars-specs.js
It looks like dumpsys output is changing between different Android versions, so I've updated the parsing rules to make it work on Android 12+. Also refactored the code to make it a bit more easier to modify and update.
Addresses https://github.com/appium/appium/issues/16390
I've only tested on Android 11 and 12 emulators. I assume more testing is necessary on older system versions though.
=> fix: Update the way system bars info is parsed

lib/webview-helpers.js
Addresses https://github.com/appium/appium/issues/16514
=> fix: Read package name from web view info if not provided explicitly

lib/commands/app-management.js
Fixes https://github.com/appium/appium/issues/16755
=> fix: use strict match for the app id in queryAppState

lib/commands/app-management.js, package.json
Related to https://github.com/appium/appium/issues/17128
=> chore: Switch to dumpsys usage if main app activity resolves to android/com.android.internal.app.ResolverActivity

lib/android-helpers.js
Related to https://github.com/appium/appium/issues/17200#issuecomment-1187576462
=> chore: Increase Settings app startup timeout for emulators

lib/commands/system-bars.js, test/unit/commands/systems-bars-specs.js
Addresses https://github.com/appium/appium/issues/17405
=> fix: Update dumpsys windows output parsing logic for API level 33

lib/android-helpers.js, test/unit/android-helper-specs.js
Related to https://github.com/appium/appium/issues/17423
=> chore: Reset mock location for third party apps if requested

lib/android-helpers.js, test/unit/android-helper-specs.js
Addresses https://github.com/appium/appium/issues/17549
=> fix: Start emulator if avd cap is defined and it is not running

lib/commands/context.js, lib/desired-caps.js, test/unit/commands/context-specs.js
Fix problem described here - https://github.com/appium/appium/issues/17639
=> feat: implement "autoWebviewName" option

lib/android-helpers.js, lib/driver.js, package.json, test/unit/android-helper-specs.js
Based on https://github.com/appium/io.appium.settings/pull/101
=> chore: Bump Appium Settings dependency

lib/android-helpers.js
Addresses https://github.com/appium/appium/issues/18233
I think for now it would be a simplest workaround we could apply there
=> fix: Increase interval for the helper app install

lib/android-helpers.js
=> chore: Enable automatic access to notifications for the settings helper

.gitignore, .husky/commit-msg, .husky/pre-commit, commitlint.config.js, package.json
=> chore: add prettier, commitlint, swap husky

lib/commands/actions.js, package.json
Addresses https://github.com/appium/appium/issues/18780
=> chore: Make sharp to an optional dependency

package.json
to fix https://github.com/appium/appium-android-driver/actions/runs/5849282844/job/15857455765?pr=836
=> chore: use newer typescript

lib/commands/deviceidle.js, lib/commands/execute.js, lib/commands/mixins.ts, lib/commands/types.ts
https://github.com/appium/appium/issues/18965
=> feat: Add mobile wrappers for 'dumpsys deviceidle' API

lib/commands/context.js, lib/helpers/webview.ts
I'd like to avoid noisy lint fixes in https://github.com/appium/appium-android-driver/pull/860 so let me apply auto hook lint only as a separate pr. This is by commit hook lint change only
=> chore: apply auto commit hook lint only

lib/commands/appearance.js, lib/commands/execute.js, lib/commands/mixins.ts, lib/commands/types.ts
Added mobile wrappers for `adb shell cmd uimode` interface
=> feat: Add support of UiModeManager service commands

lib/driver.ts
Addresses https://github.com/appium/appium/issues/19730
=> fix: Add missing mobileStartActivity import

lib/commands/device/common.js, lib/commands/time.js, lib/constraints.ts, package.json
https://sclarkso.com/tech/2021/10/05/quest-2-timezone-change-without-factory-reset.html
=> feat: Add a possibility to set device timezone

lib/commands/bluetooth.js, lib/commands/execute.js, lib/commands/types.ts, lib/driver.ts, package.json
Based on https://github.com/appium/io.appium.settings/pull/165
=> feat: Add extensions for changing bluetooth state

lib/commands/log.js
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2406/
=> fix: Add proper timestamps to server logs

lib/commands/device/utils.js, lib/commands/image-injection.js, lib/commands/types.ts, lib/constraints.ts
Related to https://github.com/appium/appium-android-driver/issues/940
=> feat: Add a capability to adjust injected image properties

lib/commands/device/common.js, lib/driver.ts
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2430
=> feat: Emit an event when syslog collection is started

package.json
to release a new one with https://github.com/appium/appium-adb/pull/773
=> chore: bump appium-adb

lib/commands/bidi/constants.ts, lib/commands/bidi/models.ts, lib/commands/bidi/types.ts, lib/commands/context/exports.js, lib/commands/log.js, lib/driver.ts, lib/index.ts, lib/utils.js
https://github.com/appium/appium/issues/20741
=> feat: Add a BiDi event upon context change

lib/commands/bidi/constants.ts, lib/commands/bidi/models.ts, lib/commands/context/exports.js
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2503
=> chore: Tune contextUpdated event generation

lib/commands/bidi/models.ts, lib/commands/bidi/types.ts
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2505
=> fix: Adjust log level for BiDi events

lib/method-map.js
https://github.com/appium/appium-xcuitest-driver/pull/2554 for android driver.
---
- `/session/:sessionId/timeouts/implicit_wait`
- timeout in w3c
- `/session/:sessionId/window/:windowhandle/size`
- [Get Window Rect](https://www.w3.org/TR/webdriver1/#dfn-get-window-rect)
- `/session/:sessionId/keys`
- w3c actions, mobile commands such as `mobile: type`
- `/session/:sessionId/element/:elementId/location`, `/session/:sessionId/element/:elementId/location`, `/session/:sessionId/element/:elementId/size`
- [Get Element Rect](https://www.w3.org/TR/webdriver1/#dfn-get-element-rect)
- `/session/:sessionId/appium/device/lock`
- `mobile: lock`
- `/session/:sessionId/appium/device/unlock`
- `mobile: unlock`
- `/session/:sessionId/appium/device/is_locked`
- `mobile: isLocked`
- …
=> chore: add deprecated marks in lib/method-map.js

lib/method-map.js
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2567
=> chore: Add geolocation endpoints to the method map

lib/commands/app-management.js, lib/commands/find.ts, lib/commands/recordscreen.js, lib/commands/streamscreen.js
use optional chain for better readability
=> refactor: use optional chain
