- ANDROID_HOME_OLD
- lib/driver.js
- test/unit/driver-specs.js
Otherwise in the mobile web flow we get:
```
error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'shell' of undefined
at AndroidDriver.checkPackagePresent$ (lib/driver.js:219:25)
at tryCatch (/Users/isaac/code/appium-repos/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/isaac/code/appium-repos/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/isaac/code/appium-repos/appium/node_modules/appium-android-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at invoke …
```
> Instantiate this.adb earlier, so it is not missing in certain steps

- lib/commands/context.js
- lib/server.js
- package.json
Move actual switching logic out, so a subclass can override. Needed for Selendroid to work.
> Move context switch out to its own method, for subclasses

- lib/driver.js
- test/functional/driver-e2e-specs.js
- test/unit/driver-specs.js
- appPackage: Backward compatibility - our docs don't suggest that we support this feature but we do in current Appium and our existing e2e tests rely on it.
- autoWebview logic
- context fix: with the additional autoWebview logic, some tests were failing from context related issues, moving the `curContext` to createSession() resolves the issues.
> flexible appPackage, autoWebview logic, Context fix

- lib/android-helpers.js
- test/unit/android-helper-specs.js
In Windows, Appium 1.5 fails when copying the apk file to the Android device:
```  
[MJSONWP] Encountered internal error running command: Error: Error executing adb
Exec. Original error: Command 'D:\\android-sdk\\platform-tools\\adb.exe -s 09e146d60bdbdad8 push C:\\Users\\username\\AppData\\Local\\Temp\\20151030-3012-1k0ss0d\\appium-app.apk C:\\data\\local\\tmp\\bb9dc6b4d478edb5ffbf6dbe1e650f72.apk' exited with code 1{"stdout":"","stderr":"failed to copy 'C:\\Users\\username\\AppData\\Local\\Temp\\20151030-3012-1k0ss0d\\appium-app.apk' to 'C:\\data\\local\\tmp\\bb9dc6b4d478edb5ffbf6dbe1e650f72.apk': Read-only file system\r\n","code":1}
```
The remote apk path should not be created with path.resolve, it's always an Android path.
> Fix remote apk path in Windows

- lib/android-helpers.js
- lib/driver.js
- test/functional/driver-e2e-specs.js
- test/unit/driver-specs.js
With this change we return the same as 1.4.
@imurchie
> getSession fix: return actual capabilities

- lib/android-helpers.js
Apparently on some phones the `/local/data/` directory requires interaction to delete. So force it.
https://github.com/appium/appium/pull/5987
> Force remove files

- .gitignore
- lib/driver.js
- package.json
- test/unit/driver-specs.js
Pass `adb` instance to Bootstrap, so environment for interacting with the device is the same throughout the chain.
> Use new bootstrap constructor

- lib/commands/actions.js
- test/functional/commands/actions-e2e-specs.js
When no metastate is sent in, in some cases (notably, the `HOME` key, `3`) the call would fail. So default to `null` rather than passing the `undefined` in.
Resolves https://github.com/appium/appium/issues/6112
> Allow no metastate to be sent for key code

- lib/commands/network.js
- lib/driver.js
This way Bootstrap can access `ignoreUnexpectedShutdown` when it errors on Windows.
cc) @imurchie
> Keep track of ignoreUnexpectedShutdown in Bootstrap

- lib/android-helpers.js
- package.json
- test/functional/android-helper-e2e-specs.js
- test/functional/commands/general-e2e-specs.js
- test/unit/android-helper-specs.js
- test/unit/commands/general-specs.js
Android 6.0 (API 23) uses 'persist.sys.locale' instead of 'persist.sys.language' and 'persist.sys.country' properties to store device language settings.
I have modified ensureDeviceLocale method to use setDeviceLanguage/Country or setDeviceLocale, depending on the API level.
This PR requires the new methods added in this appium-adb PR: https://github.com/appium/appium-adb/pull/143
> Fix ensureDeviceLocale to work with API 23

- lib/android-helpers.js
- test/unit/android-helper-specs.js
In Appium 1.5, getDeviceInfoFromCaps() fails when avd capability is configured and no device is connected.
I have moved prepareEmulator call from initDevice to getDeviceInfoFromCaps to ensure that the emulator is up before trying to access it.
This PR and https://github.com/appium/appium-adb/pull/145 fix the issue https://github.com/appium/appium/issues/6233
> Launch AVD before getting devices

- lib/android-helpers.js
- lib/driver.js
- package.json
Unlocking before pushing the app to device so that we can fail the job if it failed to unlock before installing.
I also added one second after unlock runs to actually check if the screen is unlocked cause it was failing this check when the case was that the unlock app was running and then coming back to the lock screen for some reason. 
With the changes here on the verification of the unlock screen + the changes to send to background the unlock app I was getting no false positives.
> Unlock before pushing the app to device and wait to check if screen is unlocked

- lib/driver.js
We have logic the depends on `fastReset` and `skipUninstall` but never actually set those.
Addresses https://github.com/appium/appium/issues/6274
> Handle fastReset and skipUninstall

- lib/commands/general.js
- lib/driver.js
- package.json
The selendroid driver only pulls methods from `commands`, not those in the `driver` itself.
> Move startAUT method so that it is accessible to Selendroid

- lib/commands/network.js
- package.json
- test/functional/commands/geo-location-e2e-specs.js
The code fix addresses the issue [https://github.com/appium/appium/issues/4309] on **appium 1.5** to set the Location on the Android Devices and Android Emulators.It is linked with the [appium/io.appium.settings#6] .This feature will work once the settings apk is published to npm.
set Location uses Android Service (in the settings apk )is invoked in the case of device.
Need to enable **Allow mock locations** option in the Developer Options in Device/Emulator
> setting the mock location on the device and android emulator.

- lib/desired-caps.js
- lib/driver.js
- test/unit/driver-specs.js
Add `nativeWebScreenshot` desired capability that, when set, adds screenshot path to the proxy avoid list, so native screenshot is done.
Android driver portion of https://github.com/appium/appium/issues/6425
> Add cap to not proxy web screenshot

- lib/desired-caps.js
- lib/driver.js
- test/functional/driver-e2e-specs.js
- test/unit/driver-specs.js
This is the android implementation of appium/appium-ios-driver#127, which has already been merged.
#19 looks to have added these particular restrictions. `browserName` needs to be open since that's how the Selenium Grid matches nodes. See appium/appium-ios-driver#127 for more details.
This PR also had to remove the specific check for providing `browserName` and `app` together, which was not necessary for the iOS PR. I'm not positive what the rationale for this was, I'm assuming to try and catch mistakenly providing both. However providing both still prefers `app` with a custom `browserName` (which is necessary for the Grid). Another alternative would be to check if this server is being run as a Grid node, to do this conditionally. Perhaps @jlipps can comment since he added these changes? …
> Remove restrictions on browserName and combining with app capability for Grid

- lib/driver.js
- test/unit/driver-specs.js
If we try to set the cap before initializing bootstrap then we get an error when trying to call a method on undefined.
> Make sure ignoreUnimportantViews cap gets passed through

- README.md
- lib/android-helpers.js
- test/unit/android-helper-specs.js
Here's a draft implementation for appium/appium#6473.
Tested with an Android 6.0 device and a 4.0 emulator running.
Spun up an Appium instance from the Java client with PLATFORM_VERSION = 4 and got the emulator. 6 got my phone. 5 got nothing and the server returned an error response and remained online.
Let me know what you think. Once we have quorum I'll add tests.
> Auto-select devices based on platform version

- lib/android-helpers.js
- lib/driver.js
- package.json
- test/unit/android-helper-specs.js
- test/unit/driver-specs.js
Through the research of @nghiadhd, it seems that there is a way to make unlocking Android devices less flakey. Essentially (1) manually stop the unlock helper, (2) start the unlock helper twice in succession. Locally the app unlocks consistently with this.
See https://github.com/appium/appium-android-driver/issues/146
> Further de-flaking unlock

- lib/driver.js
- test/functional/driver-e2e-specs.js
It is possible that you might want to know what the device name is that is actually running a test (see https://github.com/appium/appium/issues/6550), so add that to the caps/opts so they can be retrieved through `getSession`.
> Add device name to session information

- lib/commands/touch.js
We want to fix the release options _after_ we massage the options for the other actions. Otherwise we end up with weird offsets instead of actual positions. Fixes https://github.com/appium/appium/issues/6602
> Fix release after figure out coordinates

- lib/android-helpers.js
- lib/desired-caps.js
- lib/driver.js
- test/functional/android-helper-e2e-specs.js
- test/unit/android-helper-specs.js
Proposed change in android driver to address appium issue of adb install timeout value hardcoded.
ref: https://github.com/appium/appium-adb/issues/147
My proposal to fix is to add a new capability to appium "--adb-install-timeout"
This PR has updated and passed tests
> Replace constant REMOTE_INSTALL_TIMEOUT with androidInstallTimeout capability

- lib/driver.js
- test/unit/commands/general-specs.js
Fixes #157: Don't ignore reset capability when appActivity/appPackage are used instead of app.
> Honor reset without the app capability

- lib/android-helpers.js
- test/functional/android-helper-e2e-specs.js
- test/functional/driver-e2e-specs.js
- test/unit/android-helper-specs.js
Per my previous PR I tested the new release within Appium and I found that my original change is **defective**
ref: #161 
The opts values for localApkPath and pkg parsed in android-helpers.js : line 257 are referred incorrectly.
The tests for this PR passed, but when using official capability arguments passed from appium the appium-android-driver will fail.
I have updated use of variables localApkPath and pkg to their respective capabilities: app and appPackage.
> installApkRemotely to parse correct capabilities from opts

- lib/driver.js
A default value for this timeout is set within android-helpers.js and also exists downstream in android-adb if the cap is not provided. 
If the cap is not provided this message...
`
logger.info(`Pushing ${appPackage} to device. Will wait up to ${androidInstallTimeout} ` +
`milliseconds before aborting`);
`
...will print a timeout value of 'undefined' yet still continue with the correct default value of 90000
This PR will fix the misleading message provided to the upstream appium consumer.
Apologizes for the stacked PRs around this single change
> Set default androidInstallTimeout

- lib/commands/actions.js
- package.json
Fixes https://github.com/appium/appium/issues/3158.
Added [jimp](https://www.npmjs.com/package/jimp) as a dependency. I chose this library because it has no external/native dependencies and was simple to setup with npm.
Let me know if adding this dependency is fine and I will work a bit more on the code (mainly checking if I can easily optimize the read/rotate/write/re-read flow).
> Rotate screenshot when device is not upright

- lib/commands/actions.js
getScreenshot was broken on Windows, eg. at [this log](https://gist.github.com/tiagoshibata/040e6145250d9b36616977500c0ba4d0). Using `path.resolve` at Windows prepended the drive letter to the root of the path.
Relevant lines:
```
[debug] [ADB] Running C:\adb\platform-tools\adb.exe with args: ["-P",5037,"-s","T099706ZXD","shell","/system/bin/rm","C:\\data\\local\\tmp\\screenshot.png;","/system/bin/screencap","-p","C:\\data\\local\\tmp\\screenshot.png"]
[debug] [ADB] Running C:\adb\platform-tools\adb.exe with args: ["-P",5037,"-s","T099706ZXD","pull","C:\\data\\local\\tmp\\screenshot.png","C:\\Users\\DEWOTT\\AppData\\Local\\Temp\\appium116619-5360-196dkbl.lq6fbyy14i.png"]
[debug] [ADB] Running C:\adb\platform-tools\adb.exe with args: …
```
> Fix getScreenshot on Windows

- lib/commands/general.js
- lib/desired-caps.js
- test/functional/driver-e2e-specs.js
This is required for appium/appium#780
> Passing the appWaitDurationParam to appium-adb startApp method

- lib/driver.js
- test/unit/driver-specs.js
this ensures we don't leave procs hanging if we fail mid-start-session
fix appium/appium#6753
cc @imurchie
> ensure we shut down logcat regardless of whether bootstrap was active

- lib/commands/touch.js
- package.json
- test/unit/commands/touch-specs.js
Fixes #171.
#171 is now crashing on android bootstrap when it receives the first wait without a position. I'll fix appium-android-bootstrap to accept them.
Please don't merge yet, I'll report back when this is fully functional. Let me know if you have any commentaries about this PR.
> Fixes #171, removes unused state.touch parameters

- .gitignore
- lib/android-helpers.js
If the avd is defined and in avdArgs the -wipe-data argument is set, this update will close emulator before test to wipe its data.
This Pull Request depends on [adding killEmulator function to kill specific emulator with AVD name.](https://github.com/appium/appium-adb/pull/165), to kill emulator.
> kill emulator at start of session if -wipe-data required

- lib/commands/actions.js
making fingerprint function accessible from driver. required for proxying it with base_driver.
> adding fingerprint command

- lib/driver.js
If reboot option activated (will link pull request for that soon), it will always wipe data of emulator on start, and close emulator at the end.
It also use device name and platform version to create avd name, if it is not defined.
Android emulator sometimes get stuck if it is started for a long time without activity, and will not respond to any adb command, even if we kill adb-server, this update will kill emulator after session and wipe it on start to reduce the risk of this problem on production. the issue was already created about it. #167
> support reboot parameter for android

- lib/driver.js
If `createSession` throws exception it will try to delete session before throwing the exception. In case `deleteSession` throws another exception, appium will return `deleteSession`s exception instead of real error. If you are using grid ( + jenkins) you will see `deleteSession` error instead of the real reason.
> throw real error instead of deleteSession error

- lib/desired-caps.js
- lib/driver.js
- test/unit/driver-specs.js
First pass, just deletes any copy of the app that was made.
> Add clearSystemFiles cap to delete generated app files

- lib/driver.js
Make it easier to tell what people are running when they provide logs.
> Add driver version to logs

- lib/commands/touch.js
Some clients do not send an `options` property, particularly for the `release` action. This then fails when we hit the processing of the states.
Fixes https://github.com/appium/appium/issues/7181
> Make sure we have an options object on touch action

- lib/commands/general.js
We have a capability `dontStopAppOnReset` and also, for `startActivity`, a parameter. If the latter is explicitly set it should be used, otherwise the default should be the capability.
Fixes https://github.com/appium/appium/issues/5361
> Make sure dontStopAppOnReset cap is respected

- README.md
- lib/commands/general.js
- test/unit/commands/general-specs.js
- Get display density
- Get visibility and bounds of status bar and navigation bars
- Check if soft keyboard is present
I think this will also require updates in other packages to expose the commands/endpoints to users.
Since the commands aren't exposed by default, I tested by replacing the internals of `hideKeyboard` before moving the logic to their own commands. Tested on emulators and a device.
> Add device information commands

- lib/commands/context.js
This is useful when you are launching an app from another app.
Fixes https://github.com/appium/appium/issues/7194
> Allow way to pass chromeAndroidPackage

- lib/commands/network.js
- lib/driver.js
Fix ```acceptSslCerts``` capability for android browser
PR for https://github.com/appium/appium/issues/7326
Linked PR: https://github.com/appium/appium/pull/7325
Android driver must pass ```this.acceptSslCerts``` as third argument of ```this.bootstrap.start```
> Pass acceptSslCerts to bootstrap on start

- lib/commands/context.js
try to support wechat webview automation
detail https://testerhome.com/topics/6954
a demo for weixin (wechat) testcase
already passed by local testing
```scala
test("test weixin h5") {
val capability = new DesiredCapabilities()
capability.setCapability("app", "")
capability.setCapability("appPackage", "com.tencent.mm")
capability.setCapability("appActivity", ".ui.LauncherUI")
capability.setCapability("deviceName", "emulator-5554")
capability.setCapability("fastReset", "false")
capability.setCapability("fullReset", "false")
capability.setCapability("noReset", "true")
capability.setCapability("resetKeyboard", "true")
capability.setCapability("automationName", "appium")
capability.setCapability("platformName", "android")
capability.setCapability("chromeAndroidProcess", …
```
> add chromeAndroidProcess support

- lib/driver.js
When starting the appium server with the reboot option added from appium 1.6, sometimes get the following error.
```
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/usr/local/opt/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock' exited with code 1'; Stderr: 'error: device 'emulator-5554' not found'; Code: '1'
```
I think The above error occurs when `this.adb.killEmulator` completes earlier than `this.adb.forceStop ('io.appium.unlock')`,
So fix `this.adb.killEmulator` to be executed after `this.adb.forceStop ('io.appium.unlock')`.
> Fix reboot bug

- lib/android-helpers.js
- test/unit/android-helper-specs.js
* Enable mock location for all apps below Android 6 and set io.appium.settings as the mock location app on Android 6 and above to fix the mock location issue
This PR fixes the issue below
https://github.com/appium/appium/issues/7647
> Enable mock locations for appium settings app

- lib/android-helpers.js
- lib/driver.js
- test/functional/webview-browser-tester-e2e-specs.js
Android 7 emulators without Google Play Services doesnt have the Stock Browser or Chrome by default, it comes with *WebView Browser Tester* (chromium 51.x)
Added the package and activity to run tests over this browser, it works with chromedriver `2.23` or below, so it will work by setting a custom `chromedriverExecutable`, since `appium-chromedriver` current version is `2.26`. 
Please review @imurchie @mhan
> Add Android 7 WebView Browser Tester support

- lib/commands/general.js
Set the _stopApp_ parameter to _false_ for background command. I believe the value of _dontStopAppOnReset_ should not  affect this particular endpoint and it was just a copypaste issue.
_stopAppOnReset_ capability seems to be obsolete and is neither defined nor used anywhere else in android driver:
```
$ grep -Ri 'stopAppOnReset' *
commands/general.js:                                         dontStopAppOnReset) {
commands/general.js:  // dontStopAppOnReset is both an argument here, and a desired capability
commands/general.js:  if (!util.hasValue(dontStopAppOnReset)) {
commands/general.js:    dontStopAppOnReset = !!this.opts.dontStopAppOnReset;
commands/general.js:    stopApp: !dontStopAppOnReset
commands/general.js:    stopApp: !this.opts.dontStopAppOnReset,
desired-caps.js: …
```
> Fix the default background command behaviour and remove invalid option

- lib/driver.js
- test/functional/chrome-e2e-specs.js
- test/unit/driver-specs.js
Some Chrome browsers are failing to avoid the Welcome dialog using the `--no-first-run` flag making tests to fail. 
I look at chromeOptions args in here;
* https://sites.google.com/a/chromium.org/chromedriver/capabilities
* http://peter.sh/experiments/chromium-command-line-switches/
* https://cs.chromium.org/chromium/src/chrome/common/chrome_switches.cc?q=kNoFirstRun&sq=package:chromium&type=cs&l=487
Unless i'm wrong I believe this flag is the one that should avoid the welcome dialog, since it's working for Android 7 gms emulators that had Chrome 51, but not for Android 7.1 emus with Chrome 53. 
We can avoid this by dismissing the dialog using uiautomation
> Dismiss chrome welcome

- lib/android-helpers.js
- lib/driver.js
I dunno why, but it seems like the **avd** option is not equal to _undefined_ by default, but rather _null_
This patch should fix emulator detection for such case. See the issue report https://github.com/appium/appium/issues/8164 for the reference
> Fix emulator detection

- lib/commands/general.js
It is necessary to get activity name before to tap HOME button, but not after.
Fixes the issue https://github.com/appium/appium/issues/8252
> Fix the place where activity name is received

- lib/android-helpers.js
- lib/desired-caps.js
- test/unit/android-helper-specs.js
Add possibility to set custom android install path using `androidInstallPath` capability. On some devices internal storage has low space for pushing large apps to `/data/local/tmp` so users may want to push the app to the sdcard.
> Add androidInstallPath capability

- lib/commands/actions.js
- test/functional/commands/actions-e2e-specs.js
The new approach to screenshoting uses only one adb call instead of three and is much faster than the previous one. However, I would like to ask you guys to test the new implementation on your devices as well to make sure it works properly for all supported platforms. Thanks in advance.
> Speed up screenshoting

- lib/android-helpers.js
On Windows systems we end up with Windows-formatted paths for things on the device. See https://github.com/appium/appium/issues/8377
> Make sure remote path for apk is in posix format

- test/unit/test-helper-specs.js
The test-helper-specs tests do not account for different path segment separation characters on Windows.
I have normalized these paths so that the tests pass on Windows and also tested that the same tests pass on OSX.
> Fix test-helper-specs path related tests when running on Windows

- lib/webview-helpers.js
- test/unit/webview-helper-specs.js
There has been a long running issue with finding crosswalk webviews on Android as logged in  https://github.com/appium/appium/issues/4597
There is a two part fix:
1. Fix chromedriver (there is a patch in codereview at https://codereview.chromium.org/2375613002/)
2. Update appium-android-driver to find the corresponding crosswalk webviews (this PR)
I have updated the tests to cover this scenario and implemented the changes to the webview-helper code.
> Update webview-helpers to handle crosswalk webviews 

- lib/commands/context.js
Modified lib/commands/context.js setupNewChromedriver() method to accept the androidPackage
passed via opts.chromeOptions passed by the client in desiredCapabilities.
@dpgraham
> patch to pass android package name to chromedriver

- lib/commands/general.js
- test/functional/driver-e2e-specs.js
Add method for getting the current package. Also change tests to use these methods instead of bypassing and going to the `adb` instance. 
Route is in https://github.com/appium/appium-base-driver/pull/123
Second step in https://github.com/appium/appium/issues/5493
> Add method to get current package

- .travis.yml
- test/functional/commands/basic/attribute-e2e-specs.js
- test/functional/commands/basic/element-e2e-specs.js
- test/functional/commands/basic/general-e2e-specs.js
- test/functional/commands/basic/keyboard-e2e-specs.js
- test/functional/commands/basic/orientation-e2e-specs.js
- test/functional/commands/basic/source-e2e-specs.js
- test/functional/commands/url-e2e-specs.js
- test/functional/helpers.js
One bit of Travis has been going beyond its allotted time, because of inefficiencies in the launching of emulators on the server. So split it up to lower the time.
> Split some tests

- lib/commands/actions.js
- package.json
Trying to address the issue visible in https://gist.github.com/ajaj91/a457b8b378481f9ddee39434f3343785:
> [AndroidDriver] Cannot get screenshot data with 'adb exec-out' because of 'Command output is not a valid PNG file (fd504e47 !== 89504e47)'. Defaulting to 'adb shell' call
> Fix screenshoting with exec-out

- lib/commands/actions.js
- package.json
Do not try to pull/handle zero-sized screenshots. The screencap utility may return such if one tries to take a screenshot where this is prohibited by Android API. And there is a [complain](https://github.com/appium/appium/issues/8697) about unexpected freeze after one tries to pull zero-size screenshot from the device.
> Do not try to pull zero-size screenshots

- lib/android-helpers.js
This is a copy of https://github.com/appium/appium-android-driver/pull/239, which has been accidentally deleted before it was merged.
Addresses https://github.com/appium/appium/issues/9000
> Skip setting of mock location app for emulator

- lib/android-helpers.js
- test/functional/settings-e2e-specs.js
- test/unit/android-helper-specs.js
Real-devices on Android 7+ seems to be failing to set wifi, data settings if the io.appium.settings app is not launched prior to starting the session. 
https://github.com/appium/appium/issues/8957
Would like to have @mayureshshirodkar confirmation to verify this is not happening on Android 6 or below devices. Right now i'm out of devices.  😄
> Launch settings app

- lib/android-helpers.js
Do not fail the entire startup process for a failing mock location setup.
> Log error but do not fail if mock location setting fails

- lib/webview-helpers.js
- test/unit/webview-helper-specs.js
Rather than parsing the process name by looking at placement in relation to the headers (which is problematic, since there are sometimes no headers for particular fields, and also sometimes there are no entries for fields), use the absolute position in the line, in relation to the header.
> Fix parsing of webview process name

- lib/webview-helpers.js
- test/unit/webview-helper-specs.js
Seems that the update to parsing `ps` output broke for some devices (see https://github.com/appium/appium/issues/9245). It also seems that the `NAME` field is _always_ last, which simplifies the parsing a lot (and is how Chromium does it as well: https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/chrome/adb_impl.cc#205).
> Fix logic for getting process name from pid

- lib/android-helpers.js
- package-lock.json
- package.json
- test/functional/android-helper-e2e-specs.js
Force-upgrade settings app. We don't care about its data, so there is no reason to do a real upgrade, which fails in some cases (such as when the device has settings app version 1 on it).
Also add a flag to the function, to aid in testing.
> Add support to force upgrade settings app

- lib/android-helpers.js
- test/functional/android-helper-e2e-specs.js
- test/unit/android-helper-specs.js
If installing the unlock helper fails because an old version is there (as in https://github.com/appium/appium/issues/9394), uninstall the old version and install the new one.
> Handle incompatible unlock helper during install

- package-lock.json
- package.json
* Version 0.0.3 was broken on Node version 5 because it didn't have 'use strict'
> Updated shared-preferences-builder

- lib/desired-caps.js
- lib/driver.js
This cap is present in UIA2, but is missing here. It is necessary to fix such misconception.
> Add skipUnlock capability

- lib/commands/context.js
- test/unit/commands/context-specs.js
Despite fixes to appium-base-driver to pass along the `pageLoadStrategy` capability, it was ignored by appium-android-driver.  This PR fixes that.  A unit test is included.
> Enable page load strategy

- lib/android-helpers.js
- package.json
- test/unit/android-helper-specs.js
related issues and PRs
- https://github.com/appium/appium-adb/pull/271/files
After applying the above, I'll remove `it.skip` in this PR and confirm the test will pass.
---
update
`$ npm install && npm run mocha -- -t 360000  build/test/functional/android-helper-e2e-specs.js -i` passed against the API Level 27 device.
```js
describe('ensureDeviceLocale @skip-ci', function () {
after(async function () {
await helpers.ensureDeviceLocale(adb, 'en', 'US');
});
it('should set device language and country', async function () {
await helpers.ensureDeviceLocale(adb, 'fr', 'FR');
if (await adb.getApiLevel() < 23) {
await adb.getDeviceLanguage().should.eventually.equal('fr');
await adb.getDeviceCountry().should.eventually.equal('FR');
} else {
await …
```
> replace the set locale method

- lib/android-helpers.js
- lib/desired-caps.js
- lib/driver.js
- test/unit/android-helper-specs.js
Add `clearDeviceLogsOnStart` desired capability and pass along to ADB where necessary.
> Add clearDeviceLogsOnStart capability

- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/shell.js
- test/functional/commands/execute-e2e-specs.js
It is ok for clients to have access to extended possibilities if Appium server is running on their side.
> Allow execution of mobile:shell if relaxed security is enabled for the driver

- lib/commands/context.js
- lib/commands/general.js
- test/unit/commands/context-specs.js
**Current Behavior:**
Automation steps:
1. launch hybrid app
2. switch to webview context
3. close app
4. launch hybrid app
5. switch to webview context
6. query webview element
Result:
Error: chrome is not reachable
**New Behavior:**
Automation steps:
1. launch hybrid app
2. switch to webview context
3. close app
4. launch hybrid app
5. switch to webview context
6. query webview element
Result:
No error thrown. Element can be found.
**Implementation:**
No need to throw error about current instance of chromedriver. The code can already decide when to reuse or recreate chromedriver session.
Reset current context when app is closed thus switchContext can react properly when app relaunched.
> Implements: Keep access to chromedriver after app relaunch

- lib/commands/context.js
- lib/webview-helpers.js
- test/unit/commands/context-specs.js
Strip the `goog` prefix off `chromeOptions` if it is present. And shift `Arguments` over to `args`.
See https://github.com/appium/appium/issues/9838
> Handle Chromedriver arguments

- test/functional/driver-e2e-specs.js
- test/unit/commands/general-specs.js
- test/unit/driver-specs.js
Changes to `appium-base-driver` (https://github.com/appium/appium-base-driver/commit/9f95a75d9660c39b6f2a92689a19252b49263795) made the apk checking tests break.
Changes to `asyncbox` (https://github.com/jlipps/asyncbox/commit/155e27bfc91862cb7bfb636cb3cf11108ec37d40) made the `autoWebview` timeout test fail.
> Fix the build

- lib/commands/general.js
- test/unit/commands/general-specs.js
**Problem: context is not reset on reset command**
After invoking `driver.reset` on webview context, appium will keep telling us that chrome is not reachable although the app is up on the foreground. Apparently, switchContext was not invoked since new context is the same as last context (before reset).
Current workaround is by invoking `closeApp` before calling `reset`.
**Solution:**
Similar to `closeApp`, after `reset` we need to reset curContext as well.
> Reset context after reset

- lib/commands/recordscreen.js
- test/unit/commands/recordscreen-specs.js
Screenrecord requires some time to shutdown after SIGINT is sent to the process
> Add shutdown timeout for screen recorder process

- lib/commands/actions.js
- lib/desired-caps.js
- test/unit/commands/actions-specs.js
the endpoint in base driver requires lock to have the required `seconds` parameter. the previous implementation was ignoring it. Now this is fixed and the server will wait for given number of seconds before to unlock the screen if seconds > 0. The same behaviour is implemented for iOS.
FYI @vrunoa
> Update lock logic, so it's in sync with iOS

- lib/commands/touch.js
- test/functional/commands/touch/drag-e2e-specs.js
- test/unit/commands/touch-specs.js
It is a breaking change, but at some point of time this should be done anyway. Addresses https://github.com/appium/appium/issues/7486
> Always assume that "'press', 'moveTo', 'tap', 'longPress'" actions require absolute coordinates

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Skip setting application permissions for Settings helper if it is already installed and is running on the device. Addresses https://github.com/appium/appium/issues/10070
> Speed up driver init

- lib/commands/general.js
- lib/driver.js
- test/unit/commands/general-specs.js
- test/unit/driver-specs.js
Rather than reset to `null`, which means native and causes much problems (see https://travis-ci.org/appium/appium-uiautomator2-driver/jobs/331143446 for instance), use `'NATIVE_APP'`.
Fixes the build for https://github.com/appium/appium-uiautomator2-driver/pull/134
> Reset context to NATIVE_APP instead of null

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Unfortunately it is not possible to fully get rid of slow grantAllPermissions helper., since all application permissions are reset after `pm clear` command is executed on the application package.
> Restore application permissions after fast reset

- README.md
- lib/commands/element.js
- test/unit/commands/element-specs.js
Only this driver has no `rect` response.
```
[HTTP] <-- POST /wd/hub/session/071827a5-7d43-4a01-81b6-1f2615c23ee3/element 200 29 ms - 53
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
[HTTP] --> GET /wd/hub/session/071827a5-7d43-4a01-81b6-1f2615c23ee3/element/1/rect {}
[debug] [W3C] Calling AppiumDriver.getElementRect() with args: ["1","071827a5-7d43-4a01-81b6-1f2615c23ee3"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getRect","params":{"elementId":"1"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getRect","params":{"elementId":"1"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] …
```
> add getting element rect for uiautomator

- lib/commands/app-management.js
Currently, terminateApp returns not running error if the app process running, and fit it.
> fix process check in terminateApp

- lib/commands/touch.js
This saves some milliseconds while building gestures chain
> Do not perform unnecessary call to getSize endpoint

- lib/commands/find.js
- test/functional/commands/actions-e2e-specs.js
- test/functional/commands/basic/attribute-e2e-specs.js
- test/functional/commands/basic/element-e2e-specs.js
- test/functional/commands/find/by-accessibility-id-e2e-specs.js
- test/functional/commands/find/by-id-e2e-specs.js
- test/functional/commands/find/by-uiautomator-e2e-specs.js
- test/functional/commands/find/by-xpath-e2e-specs.js
- test/functional/commands/find/find-basic-e2e-specs.js
- test/functional/commands/find/from-el-e2e-specs.js
- test/functional/commands/find/invalid-strategy-e2e-specs.js
- test/functional/commands/geo-location-e2e-specs.js
- test/functional/commands/keyboard/keyboard-e2e-specs.js
- test/functional/commands/notifications-e2e-specs.js
- test/functional/commands/recordscreen-e2e-specs.js
- test/functional/commands/touch/drag-e2e-specs.js
- test/functional/commands/touch/multi-action-e2e-specs.js
- test/functional/commands/url-e2e-specs.js
- test/functional/webview-browser-tester-e2e-specs.js
Unit tests should (as they do) test `findElOrEls`, but the rest of the time we ought to use the base driver methods that are actually called by the protocol.
This also relieves us of the need of validating the locators, which is done already (https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/commands/find.js#L19), and leads to weird logs with multiple validation lines.
> Move to real find methods, not findByElOrEls

- lib/commands/context.js
- lib/commands/index.js
- lib/driver.js
- test/unit/driver-specs.js
Move chromedriver setup functions out of `lib/driver.js` so they are available in uiautomator2 driver. Fixes https://github.com/appium/appium/issues/10146
> Fix handling of chrome

- lib/android-helpers.js
- test/unit/android-helper-specs.js
If there are no `avdArgs` then don't include them.
Fixes https://github.com/appium/appium/issues/10177
> Do not include empty avd args

- lib/commands/general.js
- test/unit/commands/general-specs.js
When app is started using an activity but redirects to another one (or
another package) one may use appWaitPackage or appWaitActivity either
as capabilities which will be used during the initial launch, or as parameters
of the startActivity command.
Using the background command in such circumstances would lead to ADB
permission denial error (activity is not exported).
This PR fixes that issue when:
* the activity is the original session activity (launchApp command)
* the app was started using startActivity command
> Fix background when using appWaitPkg/Activity

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Setting app permissions is quite costly operation and since these are already set in `installOrUpgrade` method then there is no need to do it again for newly installed apps.
> Do not perform fast reset for newly installed apps

- lib/commands/log.js
- test/unit/commands/log-specs.js
Selenium client does not like log items, which are not compatible to LogRecord class
> Tune log entry format for bugreport output

- lib/android-helpers.js
- test/unit/android-helper-specs.js
This improves the flow of `pushStrings` helper and performs temporary resources cleanup. also it will avoid errors like https://gist.github.com/tfcardoso/355aede1f8bab333ab76e5b0a341cd79#file-cpuinfo-L177 in the log
> Tune pushStrings helper

- lib/commands/recordscreen.js
- test/unit/commands/recordscreen-specs.js
It looks like Google has finally fixed compatibility issues since Android P and from now on one can record screen on emulator the same way he does it on real devices.
> Make it possible to record screen on Android P emulators

- lib/commands/recordscreen.js
- test/unit/commands/recordscreen-specs.js
It looks like this way of terminated process detection is more precise on Android.
> Replace `kill -0` with `ps`

- .gitignore
- lib/commands/context.js
- lib/desired-caps.js
- package.json
`appium-chromedriver` can now take a directory in which CD executables are located, and a mapping file to get the correct Chrome version for a particular CD. Pass those in, from two new desired capabilities:
* `chromedriverExecutableDir` - the full path to a directory in which Chromedriver executables can be found
* `chromedriverChromeMappingFile` - the full path to a file with a JSON structure inside, mapping versions of Chromedriver to minimum versions of Chrome.
>  Send mapping and location of cds to appium-chromedriver

- lib/commands/network.js
- test/unit/commands/network-specs.js
The previous approach was not really effective if it was only necessary to change the state of the particular system, for example WiFi only without touching the others via setConnection API.
> Do not try to change connection state if it is already in correct state

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Usually third party apps only need to be reinstalled if there are new versions of them, which speeds up session initialization.
> Check other apps versions before reinstalling them

- lib/android-helpers.js
- lib/desired-caps.js
- lib/driver.js
- test/unit/android-helper-specs.js
Add a capability `adbExecTimeout` to customize the amount of time we will wait for `adb` to run. Necessary on some slow systems where timeouts happen a lot (see, for instance, the Espresso driver on Travis).
The signature for `helpers.createADB()` is too long. Change to taking an options object rather than a list of arguments. That is a breaking change.
> Add adbExecTimeout cap

- lib/android-helpers.js
- test/unit/android-helper-specs.js
This is just a suggestion.
----
I got feedback from some Appium users in Japan who faced wrong package/activity name.
We can see `Bad component name: com.android.vending` if we inserted a space in `appActivity` for example. For users, it's difficult to estimate the case.
I know the error message by adb command is a common thing for Android developers though. But in the case, users should take much time to dig into adb command world.
```
error: [MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command '/Users/itonozomi/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n 'com.android.vending /.AssetBrowserActivity' -S -a android.intent.action.MAIN -c …
```
> Add warning for apppackage, appactivity and appwaitpackages

- lib/commands/general.js
- test/unit/commands/general-specs.js
addressed : https://github.com/appium/appium/issues/10832
I made sure the format worked with emulator OS 4, 5, 6, 7, 8 and real device with 6.
Wha do you think?
----
- iOS returns JS's `Date` (both real devices and simulators):
https://github.com/appium/appium-ios-driver/blob/17ac721c3c1cbefce28445a036daf1a50f4c6d80/lib/commands/general.js#L20 
- Android's `shell date` can format.
```
1|generic_x86:/ $ date --help
usage: date [-u] [-r FILE] [-d DATE] [+DISPLAY_FORMAT] [-D SET_FORMAT] [SET]
Set/get the current date/time. With no SET shows the current date.
Default SET format is "MMDDhhmm[[CC]YY][.ss]", that's (2 digits each)
month, day, hour (0-23), and minute. Optionally century, year, and second.
Also accepts "@UNIXTIME[.FRACTION]" as seconds since midnight Jan 1 1970.
-d	Show DATE …
```
> tweak android date format

- lib/commands/find.js
- package.json
cc @mykola-mokhnach: unfortunately we can't do `instanceof` checks where the LHS could be an instance of a class from a different version of a module as the RHS.
> fix issue in find element error handling, so implicit wait can work

- lib/commands/general.js
- package.json
- test/unit/commands/general-specs.js
Related to https://github.com/appium/appium-ios-driver/pull/282
> update getDeviceTime to use cross-platform format specifiers

- lib/android-helpers.js
See https://discuss.appium.io/t/unicodeime-debug-apk-failure-install-failed-already-exists-attempt-to-re-install-io-appium-android-ime-without-first-uninstalling/21270 for more details.
Uninstalling the app from the device first sometimes helps to resolve the problem.
> Retry installation of Unicode IME helper

- lib/commands/context.js
- lib/desired-caps.js
In `appium-chromedriver` this allows users to bypass the auto-configuration, without the need to pass in the `chromedriverExecutable` with the package path in it.
> Add chromedriverUseSystemExecutable cap to pass to appium-chromedriver

- lib/android-helpers.js
- test/unit/android-helper-specs.js
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md allows to use `,` in `appWaitActivity`.
https://github.com/appium/appium/issues/11101#issuecomment-407682259
> add comma for package validation to relax the logic

- lib/desired-caps.js
webdriver standard, currently only supported by chromedriver and firefox.
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/PageLoadStrategy.html
> Add pageLoadStrategy capability now supported by chromedriver

- lib/android-helpers.js
* `capabilities must include either 'appPackage' or 'browserName'` suggests that it works fine if you have both
* Re-word it to say that you can only have one or the other (exclusive or)
(discovered through https://github.com/appium/appium-desktop/issues/624)
> Re-word cap validation errors

- lib/android-helpers.js
This will help to save time for session init if `skipUnlock` capability is truth
> Do not install unlock helper if skipUnlock is set to true

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Fix https://github.com/appium/appium/issues/11403#issuecomment-423881464
According to https://github.com/appium/appium/issues/11403#issuecomment-423881464 , `adb.pullApk` can raise an error. 
In this PR, I've added try/catch to ignore the error if `adb.pullApk` raises an error. The `app` keeps empty in the case.
I ensured this change fix the issue: https://github.com/appium/appium/issues/11403#issuecomment-423932704
---
related commit is https://github.com/appium/appium-android-driver/commit/187c66950ea430fd84704d21035c009cb4bebbc0#diff-97eeab6ebf462ba97a11ee0221ddaf13R509
> add try/catch to avoid error by pullApk in pushString

- lib/commands/context.js
we did not previously support the `loggingPrefs` capability for chrome sessions.
> support loggingPrefs capability for chrome sessions

- lib/android-helpers.js
- lib/commands/general.js
- lib/driver.js
This fixes the result of `getStrings` API call, since client libs expect `Map<String, String>` as the resulting type and we might put a list there if the particular resource value has plural options
> Fix resource strings handling

- lib/unlock-helpers.js
- package.json
- test/unit/unlock-helper-specs.js
Addresses https://github.com/appium/appium/issues/11605
> Update Enter button locator for Samsung devices

- lib/android-helpers.js
- lib/desired-caps.js
- package.json
- test/functional/android-helper-e2e-specs.js
- test/unit/android-helper-specs.js
depends on https://github.com/appium/appium-adb/pull/372
After merging the PR, we should update the module.
In this PR, I've introduced `localeScript` capability to set `Hans` in `zh-Hans-CN`. The middle one is named `script` in the Locale term. It only available in Android so far.
> add localeScript capability to set script in locale

- lib/driver.js
- test/unit/driver-specs.js
I forgot to add below for Android P..
- It needs for changing animation scale so far since `java.lang.NoSuchMethodException: setAnimationScales [class [F]` can happen.
- It only needs when animation scale changes
- But considering safe, I have called `setDefaultHiddenApiPolicy` every time
> Add hidden api policy

- lib/android-helpers.js
- package.json
- test/unit/android-helper-specs.js
Maybe, this way is simpler than _ensuring disable animation #464_ since this change fixes the animation issue in espresso-driver as well.
----
copy from #464 
I found we should have called `await this.adb.grantPermission('io.appium.settings', 'android.permission.SET_ANIMATION_SCALE');` for animation scale before changing animations.
https://github.com/appium/appium/pull/11640#issuecomment-438260477
I knew the setting app was granted permissions in the installation phase.
But I observed we must grant permission with the above command before changing animations...
After this change, I ensured the animation scale changed correctly on Android 4.4.
> grant animation scale permission after inistalling setting apk

- lib/android-helpers.js
- test/unit/android-helper-specs.js
I noticed this should have included API level 23 when I ran API level 23 emulator on my local...
https://github.com/appium/appium/pull/11640#issuecomment-438260477
> include 23 to grant permissions for setting app

- lib/android-helpers.js
- test/unit/android-helper-specs.js
https://appium.slack.com/archives/C02956V3H/p1543739923001400
`language` or `locale` is mandatory. `localeScript` is option.
We can reduce warning messages for no `language` and no `locale` case.
> Calls helpers.ensureDeviceLocale if the opts has either language or locale

- lib/driver.js
- package.json
The same fix as for https://github.com/appium/appium-xcuitest-driver/pull/841
> Do not consider app as temporary if relative app path is provided

- .travis.yml
The current order always ends with the keyboard tests running alone. Move them earlier to maximize parallel running.
> Move keyboard tests earlier in the build

- lib/android-helpers.js
- lib/desired-caps.js
New capability is introduced, which is named 'skipDeviceInitialization' to allow user for omitting phase of device initialization (waiting for device, pushing settings app, permissions). It allows to improve startup performance when device was already used for tests and all required things was setup.
> Introduce skipDeviceInitialization capability

- lib/android-helpers.js
- lib/driver.js
- test/unit/android-helper-specs.js
- test/unit/driver-specs.js
It turns out that `javaVersion` ADB argument is not used anywhere in that module. So there is no need to have this call in depending drivers.
> Update java version retrieval logic

- lib/commands/network.js
Geolocation providers require some time to get the actual info. Also, one doesn't always care about getting the current geolocation value geolocation is being set.
> Avoid throwing an error if Appium Settings fails to provide geolocation values

- lib/commands/context.js
- lib/commands/general.js
- lib/driver.js
The same exact command is already being called on `closeApp`: https://github.com/appium/appium-android-driver/blob/master/lib/commands/general.js#L262
A side note: should both of these commands respect the `recreateChromeDriverSessions` desired capability? Then we should call `suspendChromedriverProxy` instead of `stopChromedriverProxies` like here:
https://github.com/appium/appium-android-driver/blob/master/lib/commands/context.js#L71
> stop chromedriver proxies when reset command is called. fixes #12083

- lib/unlock-helpers.js
- test/unit/unlock-helper-specs.js
When I tried to pin unlock:
- some devices approve after entering pin-code, 4 digits, automatically.
- Then, clicking element raises an exception
- pin failed if pin text field already has texts before starting to input digits
- some devices have a different enter button for pin code such as Samsung devices
To avoid the error, I did:
- Call `KEYCODE_POWER` before wake up
- If the text field has texts, the texts will be clean after wake up
- If the screen already off, the screen will be on. Calling wakeup after that does not affect device state
- Calling `KEYCODE_NUMPAD_ENTER` when we tap enter key
- It can work for Samsung devices and some other devices I can test
- The keycode equals to clicking `id/key_enter`
- Calling `KEYCODE_NUMPAD_ENTER` after checking screen lock
---
I tested:
- …
> screen off before wake up to clean text field, avoid no element crash

- lib/commands/app-management.js
Since Appium 1.11 caching works properly for `configureApp` calls, so there is no need to delete applications explicitly.
Fixes https://github.com/appium/appium/issues/12318
> Avoid deleting the app on installApp call

- lib/commands/general.js
Below issue happened when they were called by `await actionFunc(appPackage);` style.
```
[HTTP] {"script":"mobile: getPermissions","args":[{"type":"granted","appPackage":"io.appium.android.apis"}]}
[debug] [W3C (5a10109b)] Calling AppiumDriver.execute() with args: ["mobile: getPermissions",[{"type":"granted","appPackage":"io.appium.android.apis"}],"5a10109b-71fc-4b25-a27f-96b6d903ecc9"]
[debug] [ADB] Retrieving granted permissions
[debug] [W3C (5a10109b)] Encountered internal error running command: TypeError: this.shell is not a function
[debug] [W3C (5a10109b)]     at shell (/Users/kazu/GitHub/appium/node_modules/appium-adb/lib/tools/adb-commands.js:314:42)
[debug] [W3C (5a10109b)]     at Generator.next (<anonymous>)
[debug] [W3C (5a10109b)]     at asyncGeneratorStep …
```
> fix TypeError: this.shell is not a function

- lib/unlock-helpers.js
added the use of the last position (and now the actions are relative to the previous rather than relative to {0,0}
> Fix pattern unlock method

- lib/commands/context.js
- lib/desired-caps.js
So that folks can send in cli flags to chromedriver.
Also, noticed that unit tests are broken on master for me, something to do with unlock specs?
> add ability for users to send in additional chromedriver args

- lib/android-helpers.js
- lib/desired-caps.js
- package.json
- test/unit/android-helper-specs.js
The default count of max apps in the remote cache is 10 per ADB instance. If this value is equal or less than zero then the remote cache will be disabled and application install will be performed with the old good `adb install` call
> Add a capability to adjust the limit of the remote cache

- lib/android-helpers.js
Reduce the probability of https://github.com/appium/io.appium.settings/issues/40#issuecomment-476593174 .
The issue happened when Appium failed to install io.appium.settings app in session creation.
I also happened once on Android P.
But once it happened, I could not reproduce it again.
so, retry once is pretty much, I think.
In this PR,
- retry once only installing helper app
- raise an error instead of just puting warning to raise error to users properly.
- If this error happens, users never can run test correctly. Thus, raising error is pretty enough, I believe.
This happened in https://github.com/appium/appium-adb/blob/b6ac33cac7f7a37a4f9dd0a516ef3694444500c5/lib/tools/apk-utils.js#L629 . 
---
- Error in `push`
```
[debug] [ADB] 'io.appium.settings' is not installed
[debug] [ADB] App …
```
> retry installHelperApp once

- lib/commands/network.js
I was surprised, but in JS `parseFloat('0.0') === 0`. And Java requires these values to be of type [double](https://discuss.appium.io/t/appium-1-9-1-issues-setting-location-on-android-device/23955/36). @imurchie Do you have any better ideas of how the cast to float zero can be implemented?
> Make sure geolocation values are cast to float

- lib/commands/execute.js
- lib/driver.js
- test/unit/driver-specs.js
Partially addresses https://github.com/appium/appium/issues/12407
It makes sense to always assume that scripts starting with `mobile:` magic always target the native context even if the current one is the web one.
> Handle `mobile:` calls in non-native context

- lib/commands/context.js
There was a bug, in the following situation:
1. User opens up AUT which has a webview
2. AUT triggers Chrome to open
3. User gets list of contexts. Now the context list correctly says [AUT, chrome]
4. User selects chrome context ("WEBVIEW_chrome")
5. User thinks they are automating the chrome context, but actually they're still automating the AUT webview (title, source, etc..., all come from the AUT webview)
This was because, whenever we set up chromedriver, we always used the AUT's android package for chromedriver to attach to.
This PR special cases the chrome webview so that we can correctly attach to its android package from chromedriver. It also makes it so this works even when the user isn't using the (extremely long) `extractChromeAndroidPackageFromContextName` capability.
> allow chrome automation even when AUT also has a webview

- lib/commands/context.js
- lib/desired-caps.js
- lib/driver.js
- package.json
this helps support the multiple webview case, and would provide a supported 'workaround' for e.g. https://github.com/appium/appium/issues/11820
> add chromedriverPorts cap which allows specifying multiple ports or a range

- lib/android-helpers.js
- lib/desired-caps.js
- package.json
- test/unit/android-helper-specs.js
Based on https://github.com/appium/appium-adb/pull/442
> Add a capability that allows to enforce build tools version

- lib/commands/touch.js
Addresses https://github.com/appium/appium/issues/12520
> Enable touch actions in web view context

- lib/commands/actions.js
- lib/commands/coverage.js
- package.json
- test/unit/commands/actions-specs.js
- test/unit/commands/recordscreen-specs.js
related to https://github.com/appium/appium-support/pull/112
To respect `--tmp` arg by the PR, `temp.path` should be `tempDir.path`.
> call tempDir from appium-support to respect --temp

- lib/commands/context.js
If `noReset` is set to `true`, use an existing Chrome. Without this a temporary profile is used for each session, so everything is new.
If `noReset` is `false` or not defined, it sill stay as `false`.
> Use existing chrome if noReset is true

- lib/commands/recordscreen.js
It is said that some phone manufacturers don't include `screenrecord` into the set of available binaries.
> Improve the error message for the missing screen recording

- lib/android-helpers.js
- package.json
- test/unit/android-helper-specs.js
Monkey tool does not respect orientation settings and thus can be harmful while running automated tests on real devices.
> Use `am start` instead of `monkey` to start the Settings helper

- lib/commands/context.js
- package.json
Based on https://github.com/appium/appium-chromedriver/pull/131
Please do not merge until the above PR is published
> Add server feature to enable automated Chromedriver downloads

- lib/commands/context.js
- lib/desired-caps.js
- lib/webview-helpers.js
- test/unit/webview-helper-specs.js
This PR fixes an odd situation which I have observed with Chrome-backed webviews on Android. Currently, Appium's code assumes that if it can find a webview-type process in `/proc/net/unix`, then a webview exists for that process.
I've noticed that this assumption is not always true. Sometimes, the process exists, and a Chrome remote debugger is even running for the process, but there are no active webview pages. In this case, Chromedriver will always fail to attach to the webview, resulting in an error like "unable to discover open pages".
This PR adds a new capability `ensureWebviewsHavePages` which, if true, attempts to verify that a webview actually has active pages before adding it to the list of contexts. This serves to prevent users from trying to connect to a webview which is …
> feat: add 'ensureWebviewsHavePages' cap

- lib/commands/general.js
- test/unit/commands/general-specs.js
By default moment.js uses the local time zone. And we need to enforce the device time zone to be used while formatting the resulting stamp.
Addresses https://discuss.appium.io/t/driver-getdevicetime-works-incorrectly-for-appium-1-7-2/27369/3
> Fix time zone formatting for device time getter

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Addresses https://discuss.appium.io/t/android-7-and-8-emulators-work-9-returns-error-message-unable-to-find-an-active-device/25129
> fix: Fix partial platform version matching

- lib/android-helpers.js
- lib/desired-caps.js
- package.json
- test/unit/android-helper-specs.js
Currently the default app installation algorithm verifies if the package with the same identifier is already present on the device and does not perform reinstall or downgrade if the installed package version is equal/greater in comparison to the current one. Although, for some users such behaviour might be undesired. The newly added capability called `enforceAppInstall` if set to `true` always enforces the installation of the current app (`app`) even if the same or the newer app version is already present on the device under test.
> feat: Add a capability for enforced app installation

- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/streamscreen.js
- lib/driver.js
- package.json
This feature does the same trick as we do in iOS, although it requires GStreamer to be installed on the host machine. As the result, it is possible now to broadcast the device screen to any MJPEG client (including Chrome browser), which might be extremely useful for further integration with Appium Desktop
> feat: Add a possibility to stream the device's screen using adb+gstreamer

- lib/commands/streamscreen.js
I think it makes sense to hide the feature under the server switch, since opening connections on any given host/port is not a very secure practice. Also added an additional `pathname` argument to have a possibility to limit the broadcast to the given secret in the pathname
> feat: Protect the screen streaming by feature setting

- lib/commands/general.js
Related to appium/appium#13663 and appium/appium-uiautomator2-driver#354, background command doesn't pass in waitDuration to appium-adb. If this is not needed, please ignore this PR.
What types of changes does your code introduce to Appium?
> fix: pass waitDuration to adb startApp

- lib/commands/network.js
unfortunately i haven't been able to test this end to end
i did test by manually inputting the adb keycode sequence and it toggled the location
this potentially fixes https://github.com/appium/appium/issues/13755
> Fix toggle_location_services not working on android 9.0 devices

- lib/android-helpers.js
- package.json
https://github.com/appium/appium/issues/13983
> feat: Add a possibility to pass a letter as a platformVersion

- lib/android-helpers.js
- lib/driver.js
- test/unit/android-helper-specs.js
Also removed the obsolete `getJavaVersion` helper, since it is not used anywhere
> chore: Add isEmulator to Android helpers

- lib/commands/general.js
- test/unit/commands/general-specs.js
https://github.com/appium/appium/issues/14000
In `reset`, `commands.startAUT` is called but it does not give `this.opts.appWaitForLaunch` to `adb.startApp`.
`commands.background` in this file already does the same thing.
> fix: Add waitForLaunch in startAUT

- lib/desired-caps.js
- lib/driver.js
- package.json
Add `ignoreHiddenApiPolicyError` to ignore permission error when set/delete hidden api policy to relax the security. Some devices like a Chinese phone raises a permission error when the adb shell is called. Potentially, the security error blocks our change settings like animation scale, but it could be ignored.
Defaults to false. (Does not ignore the error)
https://github.com/appium/appium-adb/pull/507
> feat: Add ignore hidden api policy error

- .travis.yml
- test/functional/logs-e2e-specs.js
The log broadcast test is flakey. This adds a call which will produce logs, rather than leaving it to chance.
> build: add call which will produce logs to log e2e tests

- test/functional/logs-e2e-specs.js
The last one did not work in master. 
Move the timeout so it is not waiting through the other calls. We will see.
> build: move timeout for log broadcast test

- lib/android-helpers.js
- lib/desired-caps.js
I'm facing the issue when 2 seconds is not enough in order to verify that screen was unlocked successfully. So in scope of this PR I'd like to propose the option to provide the value of this timeout as part of the desired capabilities. By default (if not provided) this timeout still will be 2 seconds.
If the name of proposed capability is fine (`unlockSuccessTimeout`), I could update the list of desired capabilities for Android.
> Provide an option to set successful unlock timeout

- lib/android-helpers.js
- lib/commands/context.js
- lib/driver.js
- lib/webview-helpers.js
Sometimes users don't really know which browser name they want (or which names exist in general). This PR fixes that
> fix: Avoid package/activity caps override if they have been already provided

- lib/commands/context.js
- lib/webview-helpers.js
This PR avoids the situation where same web view names exist on different devices and get cached interchangeably because of that.
> fix: Make sure we cache web view info per device

- lib/commands/context.js
- lib/webview-helpers.js
It also makes sense to respect `androidUseRunningApp` cap as a part of `chromeOptions`. Related to https://github.com/appium/appium/issues/12651
> fix: Add more visibility into Chromedriver caps setting

- lib/commands/touch.js
The current touch actions algorithm used in android driver is quite counter-intuitive. The `parseTouch` already precalculates absolute gesture coordinates for the given elements, however it still passes element id with absolute coordinates to the downstream helpers. As far as I can understand the element id is used as a backup value if the coordinates action fails (even in that case the backend ignores the given x and y offsets and simply uses the central element point for the action). Also, since the coordinates precalculation is done on the Appium driver side (element location+size), there are many extra server calls, which slows down gestures in general. 
I don't want to change much there because of legacy reasons. Let's just align the action executor to only pass transformed …
> fix: Only provide element id to actions where it is needed

- lib/commands/file-actions.js
This check is needed if one tries to delete a file he does not have write access to
> chore: Add file deletion validation

- lib/webview-helpers.js
Enabling this capability by default will allow to avoid unexpected freezes if returned webview(s) don't have any active pages. This is actually a breaking change, but we agreed it is safe to apply it, since the behaviour without this capability enabled looks more like a bug.
> refactor: enable ensureWebviewsHavePages by default

- lib/commands/performance.js
- test/unit/commands/performance-specs.js
related to https://github.com/appium/appium-dotnet-driver/pull/422#issuecomment-687620106
> fix: Tune CPU perf data parsing

- lib/commands/context.js
- lib/commands/execute.js
- lib/webview-helpers.js
This PR adds an endpoint named `mobile: getContexts` by reusing a logic for `ensureWebviewsHavePages`
Related to https://github.com/appium/appium/issues/14745
> feat: "mobile: getContexts" on Android

- lib/commands/general.js
- package.json
turns out a simple `await B.delay` can be off by a factor of minutes for long values. This looping strategy checks in with the actual system clock to make sure we wait long enough.
> fix: did not wait long enough for the app to come back after background

- lib/webview-helpers.js
I found a case in which `androidPackage` was `null` when `noReset` was `true` case.
Newer (Not sure which version..) chromedriver and Android OS version can ignore it, but older one (at least  4.x) raised an error invalid argument by chromedriver.
Without this `androidPackage`, the request worked.
> fix: not to set androidPackage as null for chromedriver

- lib/driver.js
- test/unit/driver-specs.js
Related to appium/appium-uiautomator2-driver#440
> fix: Align autoLaunch capability behaviour with iOS

- package.json
This is needed because appium-android-driver would require a newer version of io.appium.settings to have full functionality on proper location mocking. 
This is related to:
- **python-client** pull request: appium/python-client#594
- **io.appium.settings** pull request appium/io.appium.settings#70
- **appium-adb** pull request https://github.com/appium/appium-adb/pull/563
> chore: Increased io.appium.settings to version ^3.3.0 for compatibility reasons 

- lib/commands/touch.js
This is a shame we have all these methods in base driver while they are only needed in android driver. The next step would be to remove them from base driver for good
> refactor: Move swipe helper methods to android-driver

- lib/android-helpers.js
- lib/unlock-helpers.js
- test/unit/android-helper-specs.js
- test/unit/unlock-helper-specs.js
Some devices like Samsung have customized keyboard in `pin`.
Then, it is reliable to send keys as keycode like `password` rather than finding numbers with ids. I named the strategy as `pinWithKeyEvent` for now. (Suggestions are welcome)
As backward compatibility, `pin` should be there, but the `pinUnlockWithKeyEvent` can be used as a fallback method when no system key ids in the pin view. Afaik, this fallback is pretty enough.
---
After this change:
- https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md
- readme in uia2 and espresso
> feat: add pinWithKeyEvent to put keys one by one for pin as key evnets

- lib/android-helpers.js
- lib/commands/app-management.js
- lib/commands/context.js
- lib/webview-helpers.js
- test/unit/commands/context-specs.js
- test/unit/webview-helper-specs.js
When setting WEBVIEW_chrome context, appium-android-driver assumes that an AUT is com.android.chrome.
It is correct in most cases. However, it can be wrong when it comes to testing Chrome beta, etc.
In this PR, I would like to provide a way to test Android Chrome beta under web context.
> feat: create chrome session for beta chromes

- lib/webview-helpers.js
- package.json
Related to https://github.com/appium/appium/issues/15390#issuecomment-868864881
I still wouldn't rely on the automated port detection thing though and advice to set the `webviewDevtoolsPort` value manually for each parallel session though.
> fix: Prefer file-based lock to acquire devtools port

- lib/commands/execute.js
- lib/commands/intent.js
Also refactored existing intent-based helpers, so the intent name is not required anymore since `am` also allows to also provide the target name as a combination of `-a`/`-n` arguments
> feat: Add a possibility to send an intent broadcast with a mobile command

- lib/commands/intent.js
I forgot about key names presence requirement for extras. Now it's fixed
> fix: Parsing of extra arguments

- lib/commands/intent.js
Not sure why, but the `-p` argument of `broadcast` is not documented in the `am` output. Perhaps, it was deprecated in the recent toolkit releases?
> feat: Add package option to the broadcast extension

- lib/commands/app-management.js
Fixes https://github.com/appium/appium/issues/16427
Initially I noticed the `monkey` command failed on CI in ruby_lib_core repo.
According to https://stackoverflow.com/questions/44860475/how-to-use-the-monkey-command-with-an-android-system-that-doesnt-have-physical , it works with `--pct-syskeys 0`.
Actually it works without issues in my local env against real/emulator devices, while my env had no issues without `--pct-syskeys 0`. So, I think this should not break anything.
```
% adb -P 5037 -s D0AA002182JC0202126 shell monkey  --pct-syskeys 0 -p io.appium.android.apis -c android.intent.category.LAUNCHER 1
bash arg: --pct-syskeys
bash arg: 0
bash arg: -p
bash arg: io.appium.android.apis
bash arg: -c
bash arg: android.intent.category.LAUNCHER
bash arg: 1
args: [--pct-syskeys, 0, -p, …
```
> fix: add --pct-syskeys 0 for monkey command

- .releaserc
Let me merge this to check the rule. The expected result will be a patch release.
in addition to https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js
> chore: add patch release as chore

- lib/commands/context.js
- lib/webview-helpers.js
- test/unit/commands/context-specs.js
`isChromeSession` in `getWebViewsMapping` changed the behavior since 1.22.0, especially `mobile:getContexts`.
The option affected only `browserName: chrome` case. Then, `mobile:getContexts` returned `[]` while general get context endpoint returned `CHROME` as expected. `mobile:getContexts` and general getContext returned available contexts when non-`browserName: chrome`. It included chrome browser as well.
`Returns a webviewsMapping based on CDP endpoints` is also the description of `mobile:getContexts`.
Thus, `mobile:getContexts` returns `[]` only when `browserName: chrome` is probably no makes sense.
cc @mwakizaka 
--
for https://github.com/appium/appium/issues/16721 and https://github.com/appium/appium-android-driver/pull/699
> fix: returns all available webview information by CDP endpoints in mobile:getContexts as same as Appium 1.21.0

- lib/commands/app-management.js
- package.json
It seems like monkey could be sometimes quite unpredictable. The current method seems to be more reliable, although it only works for Android 7+ (which is anyway more than 90% of devices are running)
> refactor: Update the way apps are activated on Android 7+

- lib/commands/app-management.js
- package.json
https://github.com/appium/appium/issues/16941#issuecomment-1132448650
I found the monkey command worked kind of "resume" the app.
`adb shell am start -p <package> -c android.intent.category.LAUNCHER` seems work as same.
I'm testing on lower android such as android 6, but maybe it would be nice to keep the "resume" behavior for this.
closes https://github.com/appium/appium/issues/16967
> fix: keep resume behavior as activateApp

- lib/android-helpers.js
- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/media-projection.js
- package.json
Based on https://github.com/appium/io.appium.settings/pull/88
> feat: Add mobile wrappers for media-projection-based screen recording

- lib/android-helpers.js
- test/unit/android-helper-specs.js
Hi, team. Could we use [getRunningAVDWithRetry()](https://github.com/appium/appium-adb/blob/d047d68ed1784af88777f55b313ee466ff54cc2f/lib/tools/system-calls.js#L713) instead of getRunningAVD() ?
I occasionally run into an issue where getRunningAVD() timeouts.
```
2022-08-29 10:25:01:887 [W3C] Encountered internal error running command: Error: Error getting AVD. Original error: Did not get the initial response from the Emulator console at 127.0.0.1:5554 after 5000ms
```
I feel this is more likely to happen when running many emulator sessions in parallel. I hope retrying would mitigate this. I use old uiatutomator2 (1.57) but I believe [it happens with the latest version](https://github.com/appium/appium-uiautomator2-driver/blob/e35f1d872242c483af61a2751783e2f759ff3a39/lib/driver.js#L348).
> use getRunningAVDWithRetry instead of getRunningAVD

- lib/commands/app-management.js
- lib/commands/execute.js
It is more convenient to have mobile extensions for app management commands as these could be called in the same way from different clients and don't depend on the particular client API implementation
> feat: Provide `mobile:` wrappers for app management commands

- lib/commands/app-management.js
I observed a case an app process stopped by the forceStop, but Android restarted the process immediately. (maybe the restarted app had some service) Then, the default timeout (500ms) resulted failed to terminate the app error. This behavior itself is expected right now. The `waitForCondition` calls the given func once at least, so giving zero did not help in the case.
A user can call the same killing an app process via adb command (without the app state check after it), but it would be nice to provide a way to call only the forceStop without the app state check via the same API as terminateApp.
(I'll do later, but we should address this app state check in readme. e.g. https://github.com/appium/appium-uiautomator2-driver#mobile-terminateapp)
> feat: skip checking the app state in the terminate app

- index.js
- lib/driver.js
- lib/method-map.js
here is my first stab at this. i wrote a little script to basically generate the new method map we need. this script could be copied and changed in minor ways for every driver. it outputs a javascript object which i simply copied into the new method map declaration.
```js
const {METHOD_MAP} = require('@appium/base-driver');
const {AndroidDriver} = require('.');
const util = require('util');
const deprecatedCommandNames = {};
for (const [route, methodSpec] of Object.entries(METHOD_MAP)) {
for (const [method, commandSpec] of Object.entries(methodSpec)) {
if (commandSpec.deprecated && commandSpec.command) {
deprecatedCommandNames[commandSpec.command] = {
route,
method,
commandSpec,
};
}
}
}
const newMethodMap = {};
for (const [command, details] of Object.entries(deprecatedCommandNames)) { …
```
> fix: specify supported non-standard commands in newMethodMap

- lib/webview-helpers.js
I observed possible exception here in the middle of `mobile:getContext` command itself., but it could be ignored. Lets leave the exception as a debug log, but allow appium to proceed the `mobile:getContext` command itself. This was randomly (and occasionally) happened in my observation
```
2023-03-24 06:37:23:726 - [debug] [AndroidDriver] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
2023-03-24 06:37:23:769 - [debug] [ADB] Running '/Users/kazu/android/platform-tools/adb -P 5037 -s RFCTA0CNDAL forward tcp:10900 localabstract:webview_devtools_remote_12982'
2023-03-24 06:37:23:850 - [debug] [ADB] Removing forwarded port socket connection: 10900
2023-03-24 06:37:23:850 - [debug] [ADB] Running '/Users/kazu/android/platform-tools/adb -P 5037 -s …
```
> chore: ignore an error in collectWebviewsDetails

- lib/android-helpers.js
- test/unit/android-helper-specs.js
`initDevice` has `adb.waitForDevice()` to check if the connected device is ready. My understanding for this purpose is to ensure the connected device, especially an emulator, is ready for testing.
In my local comparison, the method could take 1 sec or around even if the connected device is ready. So far, Appium could generate an emulator in a new session request. Then, such wait for launch method is necessary to handle the device up state properly while a real device is not necessary since we expect a real device is already up. (I mean Appium does not have a feature to restart a real device in a new session request).
Thus, we can skip the device wake up check for a real device. **It will improve 1 sec and a fe**w in a new session request speed.
```
2023-04-11 06:02:07:523 - [debug] [ADB] …
```
> perf: check the device state via waitForDevice only for a emulator

- lib/commands/media-projection.js
Increase timeout of the pull command in pullRecent to 5 minutes. Videos longer than 30 minutes can take over 60s to pull.
Fixes: https://github.com/appium/appium/issues/18522
> fix: increase pull recent timeout

- lib/commands/media-projection.js
Now it's not possible to adjust the file upload timeout. With the change it's possible to provide timeout parameter in the mobile: stopMediaProjectionRecording to set the request timeout.
Over 45 minute file upload to S3 can take over 4 minutes (current default).
Fixes: https://github.com/appium/appium/issues/18549
> fix: make request timeout an option in mobileStopMediaProjectionRecording

- lib/commands/actions.js
- lib/commands/execute.js
To fix https://github.com/appium/appium/discussions/18786#discussioncomment-6227844
`driver.execute_script 'mobile: lock', {seconds: 5}` has a regression to handle the given seconds as below. Currently the `lock` does not handle it properly. This PR adds `mobileLock` method to parse the option, then gives it to existing `lock` method. I'll update uia2 driver and espresso driver later to call the `mobileLock`. (I have defined a new method to not combine arguments with existing `lock`.
```
[HTTP] --> POST /wd/hub/session/c6b8ec03-ecb3-4375-a189-0eab6e7999f6/execute/sync
[HTTP] {"script":"mobile: lock","args":[{"seconds":5}]}
[debug] [AndroidUiautomator2Driver@5576 (c6b8ec03)] Calling AppiumDriver.execute() with args: ["mobile: lock",[{"seconds":5}],"c6b8ec03-ecb3-4375-a189-0eab6e7999f6"] …
```
> feat: add mobileLock to handle an argument properly

- lib/webview-helpers.js
- test/unit/webview-helper-specs.js
https://github.com/appium/appium/issues/17528
Most diff is by `prettier`... so let me list what I did here:
- Modify `DEVTOOLS_SOCKET_PATTERN` to accept https://github.com/appium/appium/issues/17528 naming logic as well
- Define `const matchedSocketName = socketNameMatch[2];` to reduce code duplications
- Add tests. `describe('DEVTOOLS_SOCKET_PATTERN', function () {`, to check the pattern
Local run:
```
npm run test
...
438 passing (11s)
3 pending
```
> fix: relax webview match

- lib/commands/element.js
- lib/commands/general.js
- lib/commands/types.ts
- lib/constraints.ts
- lib/helpers/android.ts
- package.json
- test/unit/android-helper-specs.js
Based on https://github.com/appium/io.appium.settings/pull/126
I would like to deprecate the `unicodeKeyboard` capability in the future as it is anyway not needed.
Also, the option has been removed from input APIs as it is not used there and is a leftover from the legacy bootstrap implementation.
> feat: Add 'hideKeyboard' capability

- lib/helpers/webview.ts
Fixes https://github.com/appium/appium/issues/19533
> fix: Respect adb remote host setting while collecting CDP info

- lib/helpers/android.ts
- package.json
- test/unit/android-helper-specs.js
https://github.com/appium/appium-adb/pull/715 is required.
> fix: io.appium.settings process check with isSettingsAppServiceRunningInForeground

- lib/commands/memory.js
- lib/commands/mixins.ts
- lib/commands/types.ts
Based on https://stackoverflow.com/questions/3656594/simulate-low-battery-low-memory-in-android
> feat: Add a helper method to simulate low-memory event

- lib/commands/file-actions.js
- lib/commands/general.js
- lib/commands/media-projection.js
- lib/commands/mixins.ts
- lib/commands/network.js
- lib/driver.ts
- lib/helpers/android.ts
- lib/index.ts
- lib/stubs.ts
- package.json
- test/unit/android-helper-specs.js
- test/unit/commands/network-specs.js
This is the part of the refactoring which is supposed to move all Settings App-related APIs into the corresponding package and incapsulate them there instead of abusing appium-adb for this purpose.
> feat: Use APIs imported from the io.appium.settings package

- lib/helpers/webview.ts
Fix for https://github.com/appium/appium/issues/19678
> fix: set keepAlive false to parse webview pages correctly Node.js >=19

- lib/commands/types.ts
- lib/helpers/webview.ts
- test/unit/commands/context-specs.js
- test/unit/webview-helper-specs.js
Currently, `getContexts` returns the webview names including the unreachable ones. This PR modifies the behavior not to return those.
- ✅ unit test
With Android emulator,
1. Make an unreachable webview socket by the procedure described in https://issuetracker.google.com/issues/320819731 
2. Verify `getContexts` doesn't return the unreachable webview name
> fix: stop parsing unreachable webview names

- lib/commands/device/common.js
- test/unit/commands/device-specs.js
As https://github.com/appium/appium-android-driver/blob/884c0bcdc0661a315954c46fe98acfd3e9f9d69b/lib/commands/device/common.js#L22 ?
https://github.com/appium/appium/issues/19713
Actually, when I saw logs in the ruby_lib_core's test Appium log, it had:
```
2024-01-25 09:30:47:019 - [ADB] Running '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
2024-01-25 09:30:47:041 - [ADB] Setting device id to 
2024-01-25 09:30:47:042 - [ADB] Running '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 -s  shell getprop ro.build.version.sdk'
2024-01-25 09:30:47:194 - [ADB] Current device property 'ro.build.version.sdk': 29
2024-01-25 09:30:47:195 - [ADB] Getting device platform version
2024-01-25 09:30:47:195 - [ADB] Running …
```
> fix: calls this.opts for createBaseADB

- lib/commands/app-management.js
- lib/commands/types.ts
As same as https://github.com/appium/appium-xcuitest-driver/pull/2322 , so app installation will be skipped if the installed app is equal or greater than the installed app
https://github.com/appium/appium/issues/19754
e.g. with uia2
- `driver.execute_script "mobile: installApp", {appPath: "https://github.com/appium/ruby_lib_core/raw/master/test/functional/app/api.apk.zip", checkVersion: false}`
- `driver.execute_script "mobile: installApp", {appPath: "https://github.com/appium/ruby_lib_core/raw/master/test/functional/app/api.apk.zip", checkVersion: true}`
```
[HTTP] --> POST /session/f8146e45-e10b-4e8e-abe4-6eb9d8f927ef/execute/sync
[HTTP] {"script":"mobile: installApp","args":[{"appPath":"https://github.com/appium/ruby_lib_core/raw/master/test/functional/app/api.apk.zip"}]}
[debug] …
```
> feat: add checkVersion option for mobile:installApp

- lib/commands/recordscreen.js
There was set not enough long timeout: 1-min (default value)
- https://github.com/appium/appium/issues/19785
> chore: Add timeout option to adb.pull() in stopRecordingScreen function

- lib/commands/legacy.js
- lib/driver.ts
These handlers are still present in the base driver, but we don't want to have them to be available here. So throw a proper error message instead.
This should also allow to remove some extra code from the espresso driver afterwards
> chore: Add stubs for legacy APIs

- lib/commands/image-injection.js
- lib/commands/types.ts
- lib/driver.ts
the idea is mostly based on https://medium.com/bliblidotcom-techblog/automate-custom-image-using-android-emulator-virtual-scene-camera-817086056fca, although I've slightly improved it, so images could be injected dynamically without restarting the camera app.
> feat: Add emulator image injection feature

- lib/commands/app-management.js
- lib/commands/execute.js
- lib/commands/types.ts
- package.json
- test/unit/commands/app-management-specs.js
https://github.com/appium/appium-adb/pull/739
> feat: support user for mobile isAppInstalled

- lib/commands/intent.js
Addresses https://github.com/appium/appium-uiautomator2-driver/issues/792
> fix: Add a workaround for wrong adb exit code on service stop

- lib/commands/device/common.js
Sometimes we have a race condition when Android does not register input services soon enough after Settings app is installed. Then the following error is thrown: 
> {"tag":"InputMethodManagerService","message":"InputMethodManagerService : \"ime enable io.appium.settings/.EmptyIME\" for user #0 failed due to its unrecognized IME ID.","processId":2389,"level":"ERROR","timestamp":"2024-07-01 10:53:34.565"}
> fix: Add retry for keyboard hide

- lib/commands/app-management.js
Sometimes an app might be terminated and then immediately restored by the system. If that happens then its processes becoming different PIDs. This PR handles such situation and marks app termination as successful if all application PIDs have been changed within the given timeout
> fix: Tune application termination condition

- lib/commands/context/helpers.js
- test/unit/commands/context-specs.js
Problem: Able to receive performance log types and get performance logs when using Mobile JSON Wire protocol but unable to do the same when using W3C. 
Reason: The logging preferences are set using "goog:LoggingPrefs" in Selenium capability. "`[enablePerformanceLogging](https://github.com/appium/appium-android-driver/blob/92b51340cd976a73cb60530d6cdd6d43414b939a/lib/commands/context/helpers.js#L208)`" is deprecated and Selenium 4 does not allow passing it. However, the Appium Android driver did not account for it and set it correctly to pass it to the Appium Chromedriver. Thus, the ChromeDriver would not receive it and then create a default session with the default logging preferences i.e. `{browser: ALL}`.
Logs (when trying to use the Appium server):
Capabilities sent: 
`22024-08-28 …
> feat: support 'goog:loggingPrefs' value when creating a session

- lib/commands/device/common.js
- lib/commands/log.js
- lib/driver.ts
- lib/utils.js
Similar to https://github.com/appium/appium-xcuitest-driver/pull/2458/
> feat: Emit logs over BiDi socket

- lib/utils.js
https://github.com/appium/appium/issues/20568#issuecomment-2348207253
> fix: Strip colors from server logs

- lib/commands/device/common.js
- lib/commands/execute.js
- lib/commands/geolocation.js
- lib/driver.ts
Geolocation methods are not part of the W3C API, so it makes sense to have mobile wrappers over them to let updated clients call these APIs
> feat: Add mobile wrappers to geolocation APIs

- lib/commands/app-management.js
- lib/driver.ts
- test/unit/commands/app-management-specs.js
It looks like... the same activateApp exists in https://github.com/appium/appium-adb/blob/74fb4f0a15f8e1c1db610aa633acf856877de209/lib/tools/apk-utils.js#L1180 so we can call the adb's one instead.
> chore: use activateApp from adb

- lib/commands/context/exports.js
- lib/driver.ts
Related to https://github.com/appium/appium/issues/20710
> feat: Return default window handle in native context

- lib/commands/device/common.js
- lib/commands/device/utils.js
Currently a situation is possible when a session with noReset=true cap is started, where only appPackage is set and no appActivity. In such case the driver still tries to start the app like: `[8387f77e][AndroidUiautomator2Driver@17e6] Starting 'com.package/undefined and waiting for 'com.package/undefined'`, which obviously results into an error
> fix: Tune retrieval of package launch info

- lib/commands/app-management.js
- lib/commands/appearance.js
- lib/commands/bluetooth.js
- lib/commands/context/exports.js
- lib/commands/device/emulator-actions.js
- lib/commands/device/emulator-console.js
- lib/commands/deviceidle.js
- lib/commands/execute.js
- lib/commands/file-actions.js
- lib/commands/geolocation.js
- lib/commands/image-injection.js
- lib/commands/intent.js
- lib/commands/keyboard.js
- lib/commands/lock/exports.js
- lib/commands/media-projection.js
- lib/commands/memory.js
- lib/commands/network.js
- lib/commands/nfc.js
- lib/commands/performance.js
- lib/commands/permissions.js
- lib/commands/shell.ts
- lib/commands/streamscreen.js
- lib/commands/system-bars.js
- lib/commands/time.js
- lib/commands/types.ts
- lib/driver.ts
- lib/execute-method-map.ts
- test/unit/commands/app-management-specs.js
- test/unit/commands/emulator-actions-specs.js
BREAKING CHANGE: The following driver methods and properties were **removed**:
- executeMobile
- mobileCommandsMapping
- mobileLock
- mobilePushFile
- mobilePullFolder
- mobilePullFile
- mobileActivateApp
- mobileQueryAppState
BREAKING CHANGE: Arguments of the following driver methods were **changed**:
- mobileExecEmuConsoleCommand
- mobileShell
- mobileChangePermissions
- mobileGetPermissions
- mobilePerformEditorAction
- mobileGetDeviceTime
- mobileStartScreenStreaming
- mobileDeleteFile
- mobileIsAppInstalled
- mobileRemoveApp
- mobileTerminateApp
- mobileInstallApp
- mobileClearApp
- mobileStartService
- mobileStopService
- mobileStartActivity
- mobileBroadcast
- mobileGetContexts
- mobileUnlock
- mobileRefreshGpsCache
- mobileStartMediaProjectionRecording
- …
> feat: Add support of executeMethodMap

- lib/commands/geolocation.js
- lib/execute-method-map.ts
- package.json
Ad'satellites', 'speed', 'bearing', 'accuracy' for the mobile command.
Validation will be done in the `this.settingsApp.setGeoLocation`
> feat: extend mobile: setGeoLocation

- lib/commands/network.js
- lib/commands/types.ts
- test/unit/commands/network-specs.js
Fixes https://github.com/appium/appium-uiautomator2-driver/issues/866
- mobile:getConnectivity accepts `string`
- mobile:getConnectivity wants to return only specified service/s
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-getconnectivity
> fix: get connectivity return value

- lib/method-map.js
I'd like to deprecate this endpoint in the base driver as it is anyway only used in Android
> feat: Add /session/:sessionId/network_connection to the method map

- lib/method-map.js
- `/session/:sessionId/network_connection`
- `mobile: getConnectivity`
missed from https://github.com/appium/appium-android-driver/pull/995
> chore: add deprecated: true for network_connection

- package.json
```
kazu $ git grep 'rimraf'
CHANGELOG.md:* **deps-dev:** bump rimraf from 4.4.1 to 5.0.0 ([#794](https://github.com/appium/appium-android-driver/issues/794)) ([7ab3933](https://github.com/appium/appium-android-driver/commit/7ab39337b1190803d8bb064255570aa6b50d6c48))
CHANGELOG.md:* **deps-dev:** bump rimraf from 3.0.2 to 4.0.4 ([#783](https://github.com/appium/appium-android-driver/issues/783)) ([8f89741](https://github.com/appium/appium-android-driver/commit/8f89741d2cbba912b68ae533372dd8503db9eef1))
lib/commands/file-actions.js:    await fs.rimraf(tmpRoot);
lib/commands/geolocation.js:      await fs.rimraf(tmpRoot);
lib/commands/media-projection.js:    await fs.rimraf(path.dirname(recentRecordingPath));
lib/commands/recordscreen.js:      await this.adb.rimraf(record); …
```
> chore: drop rimraf deps from dev deps as no references
